/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_abdouwindow1 (void)
{
  GtkWidget *abdouwindow1;
  GtkWidget *fixed1;
  GtkWidget *abdoufacture;
  GtkWidget *abdoudeconnecter;
  GtkWidget *Prestation_vol;
  GtkWidget *pres_heber;

  abdouwindow1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow1), _("window1"));
  gtk_window_set_position (GTK_WINDOW (abdouwindow1), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (abdouwindow1), 1200, 1000);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (abdouwindow1), fixed1);

  abdoufacture = gtk_button_new_from_stock ("mes factures");
  gtk_widget_show (abdoufacture);
  gtk_fixed_put (GTK_FIXED (fixed1), abdoufacture, 128, 168);
  gtk_widget_set_size_request (abdoufacture, 128, 37);

  abdoudeconnecter = gtk_button_new_with_mnemonic (_("deconnecter"));
  gtk_widget_show (abdoudeconnecter);
  gtk_fixed_put (GTK_FIXED (fixed1), abdoudeconnecter, 128, 240);
  gtk_widget_set_size_request (abdoudeconnecter, 136, 37);

  Prestation_vol = gtk_button_new_with_mnemonic (_("Prestation vol"));
  gtk_widget_show (Prestation_vol);
  gtk_fixed_put (GTK_FIXED (fixed1), Prestation_vol, 128, 104);
  gtk_widget_set_size_request (Prestation_vol, 128, 29);

  pres_heber = gtk_button_new_with_mnemonic (_("Prestation hotel"));
  gtk_widget_show (pres_heber);
  gtk_fixed_put (GTK_FIXED (fixed1), pres_heber, 128, 40);
  gtk_widget_set_size_request (pres_heber, 128, 29);

  g_signal_connect ((gpointer) abdoufacture, "clicked",
                    G_CALLBACK (on_abdoufacture_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdoudeconnecter, "clicked",
                    G_CALLBACK (on_abdoudeconnecter_clicked),
                    NULL);
  g_signal_connect ((gpointer) Prestation_vol, "clicked",
                    G_CALLBACK (on_Prestation_vol_clicked),
                    NULL);
  g_signal_connect ((gpointer) pres_heber, "clicked",
                    G_CALLBACK (on_pres_heber_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow1, abdouwindow1, "abdouwindow1");
  GLADE_HOOKUP_OBJECT (abdouwindow1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (abdouwindow1, abdoufacture, "abdoufacture");
  GLADE_HOOKUP_OBJECT (abdouwindow1, abdoudeconnecter, "abdoudeconnecter");
  GLADE_HOOKUP_OBJECT (abdouwindow1, Prestation_vol, "Prestation_vol");
  GLADE_HOOKUP_OBJECT (abdouwindow1, pres_heber, "pres_heber");

  return abdouwindow1;
}

GtkWidget*
create_abdouwindow2 (void)
{
  GtkWidget *abdouwindow2;
  GtkWidget *fixed2;
  GtkWidget *abdoutreeview1;
  GtkWidget *abdousupprimer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *abdoumodifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *abdouprecedent;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *back;
  GtkWidget *abdouafficher1;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label19;

  abdouwindow2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (abdouwindow2), fixed2);

  abdoutreeview1 = gtk_tree_view_new ();
  gtk_widget_show (abdoutreeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), abdoutreeview1, 32, 104);
  gtk_widget_set_size_request (abdoutreeview1, 688, 232);

  abdousupprimer = gtk_button_new ();
  gtk_widget_show (abdousupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), abdousupprimer, 208, 408);
  gtk_widget_set_size_request (abdousupprimer, 112, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (abdousupprimer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  abdoumodifier = gtk_button_new ();
  gtk_widget_show (abdoumodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), abdoumodifier, 376, 408);
  gtk_widget_set_size_request (abdoumodifier, 96, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (abdoumodifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  abdouprecedent = gtk_button_new ();
  gtk_widget_show (abdouprecedent);
  gtk_fixed_put (GTK_FIXED (fixed2), abdouprecedent, 32, 408);
  gtk_widget_set_size_request (abdouprecedent, 112, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (abdouprecedent), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  back = gtk_label_new_with_mnemonic (_("prec\303\251dent"));
  gtk_widget_show (back);
  gtk_box_pack_start (GTK_BOX (hbox2), back, FALSE, FALSE, 0);

  abdouafficher1 = gtk_button_new ();
  gtk_widget_show (abdouafficher1);
  gtk_fixed_put (GTK_FIXED (fixed2), abdouafficher1, 544, 408);
  gtk_widget_set_size_request (abdouafficher1, 104, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (abdouafficher1), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) abdousupprimer, "clicked",
                    G_CALLBACK (on_abdousupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdoumodifier, "clicked",
                    G_CALLBACK (on_abdoumodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouprecedent, "clicked",
                    G_CALLBACK (on_abdouprecedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouafficher1, "clicked",
                    G_CALLBACK (on_abdouafficher1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow2, abdouwindow2, "abdouwindow2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdoutreeview1, "abdoutreeview1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdousupprimer, "abdousupprimer");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image2, "image2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, label3, "label3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdoumodifier, "abdoumodifier");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image4, "image4");
  GLADE_HOOKUP_OBJECT (abdouwindow2, label5, "label5");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdouprecedent, "abdouprecedent");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image3, "image3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, back, "back");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdouafficher1, "abdouafficher1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image5, "image5");
  GLADE_HOOKUP_OBJECT (abdouwindow2, label19, "label19");

  return abdouwindow2;
}

GtkWidget*
create_abdouwindow3 (void)
{
  GtkWidget *abdouwindow3;
  GtkWidget *fixed3;
  GtkWidget *abdousupp;
  GtkWidget *abdouid_supprimer;
  GtkWidget *abdouprecedent1;
  GtkWidget *abdouconfirmer;

  abdouwindow3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (abdouwindow3), fixed3);

  abdousupp = gtk_entry_new ();
  gtk_widget_show (abdousupp);
  gtk_fixed_put (GTK_FIXED (fixed3), abdousupp, 136, 120);
  gtk_widget_set_size_request (abdousupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdousupp), 8226);

  abdouid_supprimer = gtk_label_new (_("id supprimer"));
  gtk_widget_show (abdouid_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), abdouid_supprimer, 136, 56);
  gtk_widget_set_size_request (abdouid_supprimer, 120, 16);

  abdouprecedent1 = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (abdouprecedent1);
  gtk_fixed_put (GTK_FIXED (fixed3), abdouprecedent1, 112, 208);
  gtk_widget_set_size_request (abdouprecedent1, 104, 29);

  abdouconfirmer = gtk_button_new_with_mnemonic (_("appliquer"));
  gtk_widget_show (abdouconfirmer);
  gtk_fixed_put (GTK_FIXED (fixed3), abdouconfirmer, 264, 208);
  gtk_widget_set_size_request (abdouconfirmer, 112, 32);

  g_signal_connect ((gpointer) abdouprecedent1, "clicked",
                    G_CALLBACK (on_abdouprecedent1_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouconfirmer, "clicked",
                    G_CALLBACK (on_abdouconfirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow3, abdouwindow3, "abdouwindow3");
  GLADE_HOOKUP_OBJECT (abdouwindow3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdousupp, "abdousupp");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdouid_supprimer, "abdouid_supprimer");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdouprecedent1, "abdouprecedent1");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdouconfirmer, "abdouconfirmer");

  return abdouwindow3;
}

GtkWidget*
create_abdouwindow4 (void)
{
  GtkWidget *abdouwindow4;
  GtkWidget *fixed4;
  GtkWidget *abdounid;
  GtkWidget *abdounnom;
  GtkWidget *abdounprenom;
  GtkWidget *abdounreservation;
  GtkWidget *abdounmontant_total;
  GtkWidget *abdounmontant_ttc;
  GtkObject *abdounjour_adj;
  GtkWidget *abdounjour;
  GtkObject *abdounmois_adj;
  GtkWidget *abdounmois;
  GtkObject *abdounannee_adj;
  GtkWidget *abdounannee;
  GtkWidget *abdouid;
  GtkWidget *abdoulabel8;
  GtkWidget *abdoulabel9;
  GtkWidget *abdoulabel10;
  GtkWidget *abdoulabel14;
  GtkWidget *abdoulabel16;
  GtkWidget *abdoulabel13;
  GtkWidget *abdoulabel17;
  GtkWidget *abdoulabel11;
  GtkWidget *abdoumodifierr;
  GtkWidget *abdoulabel15;
  GtkWidget *abdoulabel18;
  GtkWidget *abdouvalider;
  GtkWidget *abdoulabel12;
  GtkWidget *abdou0;

  abdouwindow4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (abdouwindow4), fixed4);

  abdounid = gtk_entry_new ();
  gtk_widget_show (abdounid);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounid, 120, 40);
  gtk_widget_set_size_request (abdounid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounid), 8226);

  abdounnom = gtk_entry_new ();
  gtk_widget_show (abdounnom);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounnom, 120, 96);
  gtk_widget_set_size_request (abdounnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounnom), 8226);

  abdounprenom = gtk_entry_new ();
  gtk_widget_show (abdounprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounprenom, 120, 152);
  gtk_widget_set_size_request (abdounprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounprenom), 8226);

  abdounreservation = gtk_entry_new ();
  gtk_widget_show (abdounreservation);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounreservation, 120, 272);
  gtk_widget_set_size_request (abdounreservation, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounreservation), 8226);

  abdounmontant_total = gtk_entry_new ();
  gtk_widget_show (abdounmontant_total);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounmontant_total, 120, 328);
  gtk_widget_set_size_request (abdounmontant_total, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounmontant_total), 8226);

  abdounmontant_ttc = gtk_entry_new ();
  gtk_widget_show (abdounmontant_ttc);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounmontant_ttc, 120, 384);
  gtk_widget_set_size_request (abdounmontant_ttc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounmontant_ttc), 8226);

  abdounjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  abdounjour = gtk_spin_button_new (GTK_ADJUSTMENT (abdounjour_adj), 1, 0);
  gtk_widget_show (abdounjour);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounjour, 152, 224);
  gtk_widget_set_size_request (abdounjour, 60, 27);

  abdounmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  abdounmois = gtk_spin_button_new (GTK_ADJUSTMENT (abdounmois_adj), 1, 0);
  gtk_widget_show (abdounmois);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounmois, 312, 224);
  gtk_widget_set_size_request (abdounmois, 60, 27);

  abdounannee_adj = gtk_adjustment_new (1, 2019, 2030, 1, 10, 10);
  abdounannee = gtk_spin_button_new (GTK_ADJUSTMENT (abdounannee_adj), 1, 0);
  gtk_widget_show (abdounannee);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounannee, 464, 224);
  gtk_widget_set_size_request (abdounannee, 60, 27);

  abdouid = gtk_entry_new ();
  gtk_widget_show (abdouid);
  gtk_fixed_put (GTK_FIXED (fixed4), abdouid, 464, 32);
  gtk_widget_set_size_request (abdouid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouid), 8226);

  abdoulabel8 = gtk_label_new (_("id "));
  gtk_widget_show (abdoulabel8);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel8, 48, 48);
  gtk_widget_set_size_request (abdoulabel8, 41, 17);

  abdoulabel9 = gtk_label_new (_("nom"));
  gtk_widget_show (abdoulabel9);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel9, 40, 104);
  gtk_widget_set_size_request (abdoulabel9, 41, 17);

  abdoulabel10 = gtk_label_new (_("prenom"));
  gtk_widget_show (abdoulabel10);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel10, 32, 152);
  gtk_widget_set_size_request (abdoulabel10, 64, 25);

  abdoulabel14 = gtk_label_new (_("date"));
  gtk_widget_show (abdoulabel14);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel14, 16, 224);
  gtk_widget_set_size_request (abdoulabel14, 64, 25);

  abdoulabel16 = gtk_label_new (_("reservation"));
  gtk_widget_show (abdoulabel16);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel16, 16, 264);
  gtk_widget_set_size_request (abdoulabel16, 96, 33);

  abdoulabel13 = gtk_label_new (_("montant total"));
  gtk_widget_show (abdoulabel13);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel13, 0, 320);
  gtk_widget_set_size_request (abdoulabel13, 128, 33);

  abdoulabel17 = gtk_label_new (_("montant TTC"));
  gtk_widget_show (abdoulabel17);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel17, 0, 376);
  gtk_widget_set_size_request (abdoulabel17, 128, 33);

  abdoulabel11 = gtk_label_new (_("jour"));
  gtk_widget_show (abdoulabel11);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel11, 88, 224);
  gtk_widget_set_size_request (abdoulabel11, 56, 25);

  abdoumodifierr = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (abdoumodifierr);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoumodifierr, 144, 448);
  gtk_widget_set_size_request (abdoumodifierr, 96, 29);

  abdoulabel15 = gtk_label_new (_("mois"));
  gtk_widget_show (abdoulabel15);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel15, 248, 224);
  gtk_widget_set_size_request (abdoulabel15, 56, 25);

  abdoulabel18 = gtk_label_new (_("id facture"));
  gtk_widget_show (abdoulabel18);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel18, 384, 32);
  gtk_widget_set_size_request (abdoulabel18, 80, 25);

  abdouvalider = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (abdouvalider);
  gtk_fixed_put (GTK_FIXED (fixed4), abdouvalider, 496, 80);
  gtk_widget_set_size_request (abdouvalider, 96, 29);

  abdoulabel12 = gtk_label_new (_("annee"));
  gtk_widget_show (abdoulabel12);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel12, 392, 224);
  gtk_widget_set_size_request (abdoulabel12, 64, 25);

  abdou0 = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (abdou0);
  gtk_fixed_put (GTK_FIXED (fixed4), abdou0, 24, 496);
  gtk_widget_set_size_request (abdou0, 96, 29);

  g_signal_connect ((gpointer) abdoumodifierr, "clicked",
                    G_CALLBACK (on_abdoumodifierr_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouvalider, "clicked",
                    G_CALLBACK (on_abdouvalider_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdou0, "clicked",
                    G_CALLBACK (on_abdou0_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow4, abdouwindow4, "abdouwindow4");
  GLADE_HOOKUP_OBJECT (abdouwindow4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounid, "abdounid");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounnom, "abdounnom");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounprenom, "abdounprenom");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounreservation, "abdounreservation");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounmontant_total, "abdounmontant_total");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounmontant_ttc, "abdounmontant_ttc");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounjour, "abdounjour");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounmois, "abdounmois");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounannee, "abdounannee");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdouid, "abdouid");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel8, "abdoulabel8");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel9, "abdoulabel9");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel10, "abdoulabel10");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel14, "abdoulabel14");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel16, "abdoulabel16");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel13, "abdoulabel13");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel17, "abdoulabel17");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel11, "abdoulabel11");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoumodifierr, "abdoumodifierr");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel15, "abdoulabel15");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel18, "abdoulabel18");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdouvalider, "abdouvalider");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel12, "abdoulabel12");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdou0, "abdou0");

  return abdouwindow4;
}

GtkWidget*
create_abdouwindow5 (void)
{
  GtkWidget *abdouwindow5;
  GtkWidget *fixed5;
  GtkWidget *abdouid;
  GtkWidget *abdouprenom;
  GtkObject *abdoujour_adj;
  GtkWidget *abdoujour;
  GtkObject *abdoumois_adj;
  GtkWidget *abdoumois;
  GtkObject *abdouannee_adj;
  GtkWidget *abdouannee;
  GtkWidget *abdoureservation;
  GtkWidget *abdoumontant_total;
  GtkWidget *abdoumontant_ttc;
  GtkWidget *label29;
  GtkWidget *abdounom;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label26;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *_1546;
  GtkWidget *label33;
  GtkWidget *_87897;
  GtkWidget *abdouerreur1;
  GtkWidget *abdouerreur2;
  GtkWidget *abdouerreur3;
  GtkWidget *abdouerreur4;
  GtkWidget *abdouerreur5;
  GtkWidget *abdouerreur6;
  GtkWidget *abdouprecedent2;
  GtkWidget *abdouajoute;

  abdouwindow5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow5), _("window1"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (abdouwindow5), fixed5);

  abdouid = gtk_entry_new ();
  gtk_widget_show (abdouid);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouid, 128, 72);
  gtk_widget_set_size_request (abdouid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouid), 8226);

  abdouprenom = gtk_entry_new ();
  gtk_widget_show (abdouprenom);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouprenom, 416, 176);
  gtk_widget_set_size_request (abdouprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouprenom), 8226);

  abdoujour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  abdoujour = gtk_spin_button_new (GTK_ADJUSTMENT (abdoujour_adj), 1, 0);
  gtk_widget_show (abdoujour);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoujour, 152, 272);
  gtk_widget_set_size_request (abdoujour, 60, 27);

  abdoumois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  abdoumois = gtk_spin_button_new (GTK_ADJUSTMENT (abdoumois_adj), 1, 0);
  gtk_widget_show (abdoumois);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoumois, 280, 272);
  gtk_widget_set_size_request (abdoumois, 60, 27);

  abdouannee_adj = gtk_adjustment_new (1, 2019, 2030, 1, 10, 10);
  abdouannee = gtk_spin_button_new (GTK_ADJUSTMENT (abdouannee_adj), 1, 0);
  gtk_widget_show (abdouannee);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouannee, 392, 272);
  gtk_widget_set_size_request (abdouannee, 60, 27);

  abdoureservation = gtk_entry_new ();
  gtk_widget_show (abdoureservation);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoureservation, 120, 344);
  gtk_widget_set_size_request (abdoureservation, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoureservation), 8226);

  abdoumontant_total = gtk_entry_new ();
  gtk_widget_show (abdoumontant_total);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoumontant_total, 416, 344);
  gtk_widget_set_size_request (abdoumontant_total, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoumontant_total), 8226);

  abdoumontant_ttc = gtk_entry_new ();
  gtk_widget_show (abdoumontant_ttc);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoumontant_ttc, 416, 416);
  gtk_widget_set_size_request (abdoumontant_ttc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoumontant_ttc), 8226);

  label29 = gtk_label_new (_("date"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 24, 280);
  gtk_widget_set_size_request (label29, 49, 17);

  abdounom = gtk_entry_new ();
  gtk_widget_show (abdounom);
  gtk_fixed_put (GTK_FIXED (fixed5), abdounom, 128, 176);
  gtk_widget_set_size_request (abdounom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounom), 8226);

  label30 = gtk_label_new (_("jour"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 96, 280);
  gtk_widget_set_size_request (label30, 49, 17);

  label31 = gtk_label_new (_("mois"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 224, 280);
  gtk_widget_set_size_request (label31, 49, 17);

  label32 = gtk_label_new (_("annee"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 344, 280);
  gtk_widget_set_size_request (label32, 49, 17);

  label26 = gtk_label_new (_("id facture"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 16, 72);
  gtk_widget_set_size_request (label26, 88, 25);

  label28 = gtk_label_new (_("nom"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 40, 184);
  gtk_widget_set_size_request (label28, 49, 17);

  label27 = gtk_label_new (_("prenom"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 336, 176);
  gtk_widget_set_size_request (label27, 72, 25);

  _1546 = gtk_label_new (_("montant total"));
  gtk_widget_show (_1546);
  gtk_fixed_put (GTK_FIXED (fixed5), _1546, 296, 344);
  gtk_widget_set_size_request (_1546, 112, 25);

  label33 = gtk_label_new (_("id reservation"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 8, 344);
  gtk_widget_set_size_request (label33, 112, 25);

  _87897 = gtk_label_new (_("montant ttc"));
  gtk_widget_show (_87897);
  gtk_fixed_put (GTK_FIXED (fixed5), _87897, 296, 416);
  gtk_widget_set_size_request (_87897, 112, 25);

  abdouerreur1 = gtk_label_new ("");
  gtk_widget_show (abdouerreur1);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur1, 128, 104);
  gtk_widget_set_size_request (abdouerreur1, 160, 17);

  abdouerreur2 = gtk_label_new ("");
  gtk_widget_show (abdouerreur2);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur2, 128, 208);
  gtk_widget_set_size_request (abdouerreur2, 160, 17);

  abdouerreur3 = gtk_label_new ("");
  gtk_widget_show (abdouerreur3);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur3, 416, 200);
  gtk_widget_set_size_request (abdouerreur3, 160, 25);

  abdouerreur4 = gtk_label_new ("");
  gtk_widget_show (abdouerreur4);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur4, 120, 376);
  gtk_widget_set_size_request (abdouerreur4, 160, 25);

  abdouerreur5 = gtk_label_new ("");
  gtk_widget_show (abdouerreur5);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur5, 416, 376);
  gtk_widget_set_size_request (abdouerreur5, 160, 24);

  abdouerreur6 = gtk_label_new ("");
  gtk_widget_show (abdouerreur6);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur6, 416, 456);
  gtk_widget_set_size_request (abdouerreur6, 160, 24);

  abdouprecedent2 = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (abdouprecedent2);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouprecedent2, 48, 504);
  gtk_widget_set_size_request (abdouprecedent2, 136, 29);

  abdouajoute = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (abdouajoute);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouajoute, 424, 504);
  gtk_widget_set_size_request (abdouajoute, 112, 29);

  g_signal_connect ((gpointer) abdouprecedent2, "clicked",
                    G_CALLBACK (on_abdouprecedent2_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouajoute, "clicked",
                    G_CALLBACK (on_abdouajoute_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow5, abdouwindow5, "abdouwindow5");
  GLADE_HOOKUP_OBJECT (abdouwindow5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouid, "abdouid");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouprenom, "abdouprenom");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoujour, "abdoujour");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoumois, "abdoumois");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouannee, "abdouannee");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoureservation, "abdoureservation");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoumontant_total, "abdoumontant_total");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoumontant_ttc, "abdoumontant_ttc");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label29, "label29");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdounom, "abdounom");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label30, "label30");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label31, "label31");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label32, "label32");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label26, "label26");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label28, "label28");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label27, "label27");
  GLADE_HOOKUP_OBJECT (abdouwindow5, _1546, "_1546");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label33, "label33");
  GLADE_HOOKUP_OBJECT (abdouwindow5, _87897, "_87897");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur1, "abdouerreur1");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur2, "abdouerreur2");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur3, "abdouerreur3");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur4, "abdouerreur4");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur5, "abdouerreur5");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur6, "abdouerreur6");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouprecedent2, "abdouprecedent2");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouajoute, "abdouajoute");

  return abdouwindow5;
}

GtkWidget*
create_abdouwindow6 (void)
{
  GtkWidget *abdouwindow6;
  GtkWidget *fixed6;
  GtkWidget *abdouloginentry;
  GtkWidget *abdoumotdepasse;
  GtkWidget *abdouerreuruser;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *abdoulogin;
  GtkWidget *abdouretour;

  abdouwindow6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow6), _("abdouwindow6"));
  gtk_window_set_position (GTK_WINDOW (abdouwindow6), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (abdouwindow6), 1200, 1000);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (abdouwindow6), fixed6);

  abdouloginentry = gtk_entry_new ();
  gtk_widget_show (abdouloginentry);
  gtk_fixed_put (GTK_FIXED (fixed6), abdouloginentry, 528, 224);
  gtk_widget_set_size_request (abdouloginentry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouloginentry), 8226);

  abdoumotdepasse = gtk_entry_new ();
  gtk_widget_show (abdoumotdepasse);
  gtk_fixed_put (GTK_FIXED (fixed6), abdoumotdepasse, 528, 328);
  gtk_widget_set_size_request (abdoumotdepasse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoumotdepasse), 8226);

  abdouerreuruser = gtk_label_new ("");
  gtk_widget_show (abdouerreuruser);
  gtk_fixed_put (GTK_FIXED (fixed6), abdouerreuruser, 512, 416);
  gtk_widget_set_size_request (abdouerreuruser, 312, 49);

  label34 = gtk_label_new (_("Login"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 392, 224);
  gtk_widget_set_size_request (label34, 72, 25);

  label35 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 376, 328);
  gtk_widget_set_size_request (label35, 96, 25);

  abdoulogin = gtk_button_new_with_mnemonic (_("Login "));
  gtk_widget_show (abdoulogin);
  gtk_fixed_put (GTK_FIXED (fixed6), abdoulogin, 656, 512);
  gtk_widget_set_size_request (abdoulogin, 68, 29);

  abdouretour = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (abdouretour);
  gtk_fixed_put (GTK_FIXED (fixed6), abdouretour, 328, 512);
  gtk_widget_set_size_request (abdouretour, 104, 29);

  g_signal_connect ((gpointer) abdoulogin, "clicked",
                    G_CALLBACK (on_abdoulogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouretour, "clicked",
                    G_CALLBACK (on_abdouretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow6, abdouwindow6, "abdouwindow6");
  GLADE_HOOKUP_OBJECT (abdouwindow6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdouloginentry, "abdouloginentry");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdoumotdepasse, "abdoumotdepasse");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdouerreuruser, "abdouerreuruser");
  GLADE_HOOKUP_OBJECT (abdouwindow6, label34, "label34");
  GLADE_HOOKUP_OBJECT (abdouwindow6, label35, "label35");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdoulogin, "abdoulogin");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdouretour, "abdouretour");

  return abdouwindow6;
}
////////////////////////////////////////rana/////////////////////////////
GtkWidget*
create_rbfwindow1 (void)
{
  GtkWidget *rbfwindow1;
  GtkWidget *rbffixed1;
  GtkWidget *rbfDuree_vol;
  GtkWidget *rbfPrix_vol;
  GtkWidget *rbfId_vol;
  GtkWidget *rbfNbre_voyageurs;
  GtkObject *rbfJour_adj;
  GtkWidget *rbfJour;
  GtkObject *rbfAnnee_adj;
  GtkWidget *rbfAnnee;
  GtkObject *rbfMois_adj;
  GtkWidget *rbfMois;
  GtkWidget *rbflabelVille_arrivee;
  GtkWidget *rbflabel31;
  GtkWidget *rbflabelPrix_vol;
  GtkWidget *rbflabelClasse;
  GtkWidget *rbflabelDate_depart;
  GtkWidget *rbflabelVille_depart;
  GtkWidget *rbflabel13;
  GtkWidget *rbflabel15;
  GtkWidget *rbflabel14;
  GtkWidget *rbflabelDuree_vol;
  GtkWidget *rbflabelId_vol;
  GtkWidget *rbflabelNbre_voyageurs;
  GtkWidget *rbfcombobox1;
  GtkWidget *rbfcombobox2;
  GtkWidget *rbfcombobox3;
  GtkWidget *rbfajouter;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label29;
  GtkWidget *rbfbutton4return;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image17;
  GtkWidget *label74;

  rbfwindow1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rbfwindow1), _("window1"));
  gtk_window_set_position (GTK_WINDOW (rbfwindow1), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_gravity (GTK_WINDOW (rbfwindow1), GDK_GRAVITY_CENTER);

  rbffixed1 = gtk_fixed_new ();
  gtk_widget_show (rbffixed1);
  gtk_container_add (GTK_CONTAINER (rbfwindow1), rbffixed1);

  rbfDuree_vol = gtk_entry_new ();
  gtk_widget_show (rbfDuree_vol);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfDuree_vol, 720, 120);
  gtk_widget_set_size_request (rbfDuree_vol, 192, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfDuree_vol), 8226);

  rbfPrix_vol = gtk_entry_new ();
  gtk_widget_show (rbfPrix_vol);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfPrix_vol, 176, 280);
  gtk_widget_set_size_request (rbfPrix_vol, 168, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfPrix_vol), 8226);

  rbfId_vol = gtk_entry_new ();
  gtk_widget_show (rbfId_vol);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfId_vol, 720, 240);
  gtk_widget_set_size_request (rbfId_vol, 192, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfId_vol), 8226);

  rbfNbre_voyageurs = gtk_entry_new ();
  gtk_widget_show (rbfNbre_voyageurs);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfNbre_voyageurs, 728, 176);
  gtk_widget_set_size_request (rbfNbre_voyageurs, 184, 40);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfNbre_voyageurs), 8226);

  rbfJour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  rbfJour = gtk_spin_button_new (GTK_ADJUSTMENT (rbfJour_adj), 1, 0);
  gtk_widget_show (rbfJour);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfJour, 216, 152);
  gtk_widget_set_size_request (rbfJour, 48, 24);

  rbfAnnee_adj = gtk_adjustment_new (1, 1990, 2022, 1, 10, 10);
  rbfAnnee = gtk_spin_button_new (GTK_ADJUSTMENT (rbfAnnee_adj), 1, 0);
  gtk_widget_show (rbfAnnee);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfAnnee, 440, 152);
  gtk_widget_set_size_request (rbfAnnee, 60, 27);

  rbfMois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  rbfMois = gtk_spin_button_new (GTK_ADJUSTMENT (rbfMois_adj), 1, 0);
  gtk_widget_show (rbfMois);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfMois, 320, 152);
  gtk_widget_set_size_request (rbfMois, 60, 27);

  rbflabelVille_arrivee = gtk_label_new (_("Ville d'arriv\303\251e"));
  gtk_widget_show (rbflabelVille_arrivee);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelVille_arrivee, 552, 64);
  gtk_widget_set_size_request (rbflabelVille_arrivee, 104, 40);

  rbflabel31 = gtk_label_new (_("Ajout des vols"));
  gtk_widget_show (rbflabel31);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabel31, 368, 24);
  gtk_widget_set_size_request (rbflabel31, 120, 24);

  rbflabelPrix_vol = gtk_label_new (_("Prix du vol"));
  gtk_widget_show (rbflabelPrix_vol);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelPrix_vol, 72, 280);
  gtk_widget_set_size_request (rbflabelPrix_vol, 88, 40);

  rbflabelClasse = gtk_label_new (_("Classe"));
  gtk_widget_show (rbflabelClasse);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelClasse, 96, 208);
  gtk_widget_set_size_request (rbflabelClasse, 56, 40);

  rbflabelDate_depart = gtk_label_new (_("Date de d\303\251part: "));
  gtk_widget_show (rbflabelDate_depart);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelDate_depart, 16, 144);
  gtk_widget_set_size_request (rbflabelDate_depart, 152, 48);

  rbflabelVille_depart = gtk_label_new (_("Ville de d\303\251part"));
  gtk_widget_show (rbflabelVille_depart);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelVille_depart, 16, 56);
  gtk_widget_set_size_request (rbflabelVille_depart, 136, 40);

  rbflabel13 = gtk_label_new (_("Jour"));
  gtk_widget_show (rbflabel13);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabel13, 168, 152);
  gtk_widget_set_size_request (rbflabel13, 56, 24);

  rbflabel15 = gtk_label_new (_("Mois"));
  gtk_widget_show (rbflabel15);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabel15, 264, 152);
  gtk_widget_set_size_request (rbflabel15, 56, 24);

  rbflabel14 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (rbflabel14);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabel14, 384, 152);
  gtk_widget_set_size_request (rbflabel14, 56, 24);

  rbflabelDuree_vol = gtk_label_new (_("Dur\303\251e de vol"));
  gtk_widget_show (rbflabelDuree_vol);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelDuree_vol, 544, 112);
  gtk_widget_set_size_request (rbflabelDuree_vol, 128, 48);

  rbflabelId_vol = gtk_label_new (_("Id du vol"));
  gtk_widget_show (rbflabelId_vol);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelId_vol, 568, 240);
  gtk_widget_set_size_request (rbflabelId_vol, 72, 40);

  rbflabelNbre_voyageurs = gtk_label_new (_("Nombre des voyageurs"));
  gtk_widget_show (rbflabelNbre_voyageurs);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbflabelNbre_voyageurs, 504, 176);
  gtk_widget_set_size_request (rbflabelNbre_voyageurs, 200, 40);

  rbfcombobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (rbfcombobox1);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfcombobox1, 160, 64);
  gtk_widget_set_size_request (rbfcombobox1, 208, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Djerba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Tabarka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox1), _("Tunis"));

  rbfcombobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (rbfcombobox2);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfcombobox2, 728, 64);
  gtk_widget_set_size_request (rbfcombobox2, 184, 39);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("Amsterdam"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("Barcelone"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("Berlin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("Istanbul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("London"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox2), _("Paris"));

  rbfcombobox3 = gtk_combo_box_new_text ();
  gtk_widget_show (rbfcombobox3);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfcombobox3, 176, 208);
  gtk_widget_set_size_request (rbfcombobox3, 155, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox3), _("Business"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox3), _("First_class"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox3), _("Economy"));

  rbfajouter = gtk_button_new ();
  gtk_widget_show (rbfajouter);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfajouter, 136, 360);
  gtk_widget_set_size_request (rbfajouter, 184, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (rbfajouter), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("Ajouter vol"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox4), label29, FALSE, FALSE, 0);

  rbfbutton4return = gtk_button_new ();
  gtk_widget_show (rbfbutton4return);
  gtk_fixed_put (GTK_FIXED (rbffixed1), rbfbutton4return, 680, 360);
  gtk_widget_set_size_request (rbfbutton4return, 142, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (rbfbutton4return), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image17 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox17), image17, FALSE, FALSE, 0);

  label74 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label74);
  gtk_box_pack_start (GTK_BOX (hbox17), label74, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) rbfajouter, "clicked",
                    G_CALLBACK (rbfon_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfbutton4return, "clicked",
                    G_CALLBACK (rbfon_button4return_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rbfwindow1, rbfwindow1, "rbfwindow1");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbffixed1, "rbffixed1");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfDuree_vol, "rbfDuree_vol");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfPrix_vol, "rbfPrix_vol");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfId_vol, "rbfId_vol");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfNbre_voyageurs, "rbfNbre_voyageurs");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfJour, "rbfJour");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfAnnee, "rbfAnnee");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfMois, "rbfMois");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelVille_arrivee, "rbflabelVille_arrivee");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabel31, "rbflabel31");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelPrix_vol, "rbflabelPrix_vol");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelClasse, "rbflabelClasse");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelDate_depart, "rbflabelDate_depart");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelVille_depart, "rbflabelVille_depart");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabel13, "rbflabel13");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabel15, "rbflabel15");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabel14, "rbflabel14");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelDuree_vol, "rbflabelDuree_vol");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelId_vol, "rbflabelId_vol");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbflabelNbre_voyageurs, "rbflabelNbre_voyageurs");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfcombobox1, "rbfcombobox1");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfcombobox2, "rbfcombobox2");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfcombobox3, "rbfcombobox3");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfajouter, "rbfajouter");
  GLADE_HOOKUP_OBJECT (rbfwindow1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (rbfwindow1, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (rbfwindow1, image4, "image4");
  GLADE_HOOKUP_OBJECT (rbfwindow1, label29, "label29");
  GLADE_HOOKUP_OBJECT (rbfwindow1, rbfbutton4return, "rbfbutton4return");
  GLADE_HOOKUP_OBJECT (rbfwindow1, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (rbfwindow1, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (rbfwindow1, image17, "image17");
  GLADE_HOOKUP_OBJECT (rbfwindow1, label74, "label74");

  return rbfwindow1;
}

GtkWidget*
create_rbfwindowaffichage (void)
{
  GtkWidget *rbfwindowaffichage;
  GtkWidget *rbffixed2;
  GtkWidget *rbftreeview1;
  GtkWidget *rbflabelrbflistvol;
  GtkWidget *rbfretour;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label12;

  rbfwindowaffichage = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rbfwindowaffichage, 1200, 400);
  gtk_window_set_title (GTK_WINDOW (rbfwindowaffichage), _("window2"));
  gtk_window_set_position (GTK_WINDOW (rbfwindowaffichage), GTK_WIN_POS_CENTER_ALWAYS);

  rbffixed2 = gtk_fixed_new ();
  gtk_widget_show (rbffixed2);
  gtk_container_add (GTK_CONTAINER (rbfwindowaffichage), rbffixed2);

  rbftreeview1 = gtk_tree_view_new ();
  gtk_widget_show (rbftreeview1);
  gtk_fixed_put (GTK_FIXED (rbffixed2), rbftreeview1, 32, 56);
  gtk_widget_set_size_request (rbftreeview1, 1104, 240);

  rbflabelrbflistvol = gtk_label_new (_("Liste des vols"));
  gtk_widget_show (rbflabelrbflistvol);
  gtk_fixed_put (GTK_FIXED (rbffixed2), rbflabelrbflistvol, 272, 8);
  gtk_widget_set_size_request (rbflabelrbflistvol, 120, 32);

  rbfretour = gtk_button_new ();
  gtk_widget_show (rbfretour);
  gtk_fixed_put (GTK_FIXED (rbffixed2), rbfretour, 40, 336);
  gtk_widget_set_size_request (rbfretour, 80, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (rbfretour), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox1), label12, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) rbfretour, "clicked",
                    G_CALLBACK (rbfon_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rbfwindowaffichage, rbfwindowaffichage, "rbfwindowaffichage");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, rbffixed2, "rbffixed2");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, rbftreeview1, "rbftreeview1");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, rbflabelrbflistvol, "rbflabelrbflistvol");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, rbfretour, "rbfretour");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, image1, "image1");
  GLADE_HOOKUP_OBJECT (rbfwindowaffichage, label12, "label12");

  return rbfwindowaffichage;
}

GtkWidget*
create_rbfwindow3 (void)
{
  GtkWidget *rbfwindow3;
  GtkWidget *rbffixed3;
  GtkObject *rbfspinbutton123_adj;
  GtkWidget *rbfspinbutton123;
  GtkObject *rbfspinbutton223_adj;
  GtkWidget *rbfspinbutton223;
  GtkWidget *rbfentry123;
  GtkWidget *rbfentry223;
  GtkWidget *rbfentry323;
  GtkWidget *rbfentry423;
  GtkWidget *rbflabel17;
  GtkWidget *rbflabel24;
  GtkWidget *rbflabel26;
  GtkWidget *rbflabel23;
  GtkWidget *rbflabel18;
  GtkWidget *rbflabel25;
  GtkWidget *rbflabel27;
  GtkWidget *rbflabel32;
  GtkObject *rbfspinbutton323_adj;
  GtkWidget *rbfspinbutton323;
  GtkWidget *rbflabel20;
  GtkWidget *rbflabel21;
  GtkWidget *rbflabel22;
  GtkWidget *rbflabel19;
  GtkWidget *rbfcombobox4;
  GtkWidget *rbfcombobox5;
  GtkWidget *rbfcombobox6;
  GtkWidget *rbfbuttonconfirm;
  GtkWidget *rbfbuttonretour5;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image18;
  GtkWidget *label75;

  rbfwindow3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rbfwindow3, 1000, 500);
  gtk_window_set_title (GTK_WINDOW (rbfwindow3), _("window3"));
  gtk_window_set_position (GTK_WINDOW (rbfwindow3), GTK_WIN_POS_CENTER_ALWAYS);

  rbffixed3 = gtk_fixed_new ();
  gtk_widget_show (rbffixed3);
  gtk_container_add (GTK_CONTAINER (rbfwindow3), rbffixed3);

  rbfspinbutton123_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  rbfspinbutton123 = gtk_spin_button_new (GTK_ADJUSTMENT (rbfspinbutton123_adj), 1, 0);
  gtk_widget_show (rbfspinbutton123);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfspinbutton123, 192, 128);
  gtk_widget_set_size_request (rbfspinbutton123, 60, 27);

  rbfspinbutton223_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  rbfspinbutton223 = gtk_spin_button_new (GTK_ADJUSTMENT (rbfspinbutton223_adj), 1, 0);
  gtk_widget_show (rbfspinbutton223);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfspinbutton223, 304, 128);
  gtk_widget_set_size_request (rbfspinbutton223, 60, 27);

  rbfentry123 = gtk_entry_new ();
  gtk_widget_show (rbfentry123);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfentry123, 624, 128);
  gtk_widget_set_size_request (rbfentry123, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfentry123), 8226);

  rbfentry223 = gtk_entry_new ();
  gtk_widget_show (rbfentry223);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfentry223, 624, 176);
  gtk_widget_set_size_request (rbfentry223, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfentry223), 8226);

  rbfentry323 = gtk_entry_new ();
  gtk_widget_show (rbfentry323);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfentry323, 176, 224);
  gtk_widget_set_size_request (rbfentry323, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfentry323), 8226);

  rbfentry423 = gtk_entry_new ();
  gtk_widget_show (rbfentry423);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfentry423, 624, 224);
  gtk_widget_set_size_request (rbfentry423, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfentry423), 8226);

  rbflabel17 = gtk_label_new (_("Ville de d\303\251part"));
  gtk_widget_show (rbflabel17);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel17, 56, 72);
  gtk_widget_set_size_request (rbflabel17, 120, 32);

  rbflabel24 = gtk_label_new (_("Classe"));
  gtk_widget_show (rbflabel24);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel24, 112, 176);
  gtk_widget_set_size_request (rbflabel24, 64, 32);

  rbflabel26 = gtk_label_new (_("Prix du vol"));
  gtk_widget_show (rbflabel26);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel26, 88, 224);
  gtk_widget_set_size_request (rbflabel26, 88, 32);

  rbflabel23 = gtk_label_new (_("Dur\303\251e de vol"));
  gtk_widget_show (rbflabel23);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel23, 528, 128);
  gtk_widget_set_size_request (rbflabel23, 96, 32);

  rbflabel18 = gtk_label_new (_("Ville d'arriv\303\251e"));
  gtk_widget_show (rbflabel18);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel18, 520, 72);
  gtk_widget_set_size_request (rbflabel18, 104, 32);

  rbflabel25 = gtk_label_new (_("Nombre de voyageurs"));
  gtk_widget_show (rbflabel25);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel25, 464, 176);
  gtk_widget_set_size_request (rbflabel25, 160, 32);

  rbflabel27 = gtk_label_new (_("Id du vol"));
  gtk_widget_show (rbflabel27);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel27, 552, 224);
  gtk_widget_set_size_request (rbflabel27, 80, 32);

  rbflabel32 = gtk_label_new (_("Informations \303\240 modifier"));
  gtk_widget_show (rbflabel32);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel32, 320, 16);
  gtk_widget_set_size_request (rbflabel32, 176, 32);

  rbfspinbutton323_adj = gtk_adjustment_new (1, 2019, 2022, 1, 10, 10);
  rbfspinbutton323 = gtk_spin_button_new (GTK_ADJUSTMENT (rbfspinbutton323_adj), 1, 0);
  gtk_widget_show (rbfspinbutton323);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfspinbutton323, 424, 128);
  gtk_widget_set_size_request (rbfspinbutton323, 60, 30);

  rbflabel20 = gtk_label_new (_("Jour"));
  gtk_widget_show (rbflabel20);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel20, 144, 128);
  gtk_widget_set_size_request (rbflabel20, 48, 32);

  rbflabel21 = gtk_label_new (_("Mois"));
  gtk_widget_show (rbflabel21);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel21, 248, 128);
  gtk_widget_set_size_request (rbflabel21, 57, 32);

  rbflabel22 = gtk_label_new (_("Ann\303\251e"));
  gtk_widget_show (rbflabel22);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel22, 368, 128);
  gtk_widget_set_size_request (rbflabel22, 57, 32);

  rbflabel19 = gtk_label_new (_("Date de d\303\251part"));
  gtk_widget_show (rbflabel19);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbflabel19, 16, 128);
  gtk_widget_set_size_request (rbflabel19, 120, 32);

  rbfcombobox4 = gtk_combo_box_new_text ();
  gtk_widget_show (rbfcombobox4);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfcombobox4, 168, 72);
  gtk_widget_set_size_request (rbfcombobox4, 155, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Djerba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Sfax"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Tabarka"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Tozeur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox4), _("Tunis"));

  rbfcombobox5 = gtk_combo_box_new_text ();
  gtk_widget_show (rbfcombobox5);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfcombobox5, 624, 72);
  gtk_widget_set_size_request (rbfcombobox5, 155, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("Amsterdam"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("Barcelone"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("Berlin"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("Canada"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("Istanbul"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("London"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox5), _("Paris"));

  rbfcombobox6 = gtk_combo_box_new_text ();
  gtk_widget_show (rbfcombobox6);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfcombobox6, 176, 176);
  gtk_widget_set_size_request (rbfcombobox6, 155, 31);
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox6), _("Business"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox6), _("First_class"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (rbfcombobox6), _("Economy"));

  rbfbuttonconfirm = gtk_button_new_with_mnemonic (_("confirmation"));
  gtk_widget_show (rbfbuttonconfirm);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfbuttonconfirm, 616, 288);
  gtk_widget_set_size_request (rbfbuttonconfirm, 176, 48);

  rbfbuttonretour5 = gtk_button_new ();
  gtk_widget_show (rbfbuttonretour5);
  gtk_fixed_put (GTK_FIXED (rbffixed3), rbfbuttonretour5, 104, 400);
  gtk_widget_set_size_request (rbfbuttonretour5, 88, 29);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (rbfbuttonretour5), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image18 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_box_pack_start (GTK_BOX (hbox18), image18, FALSE, FALSE, 0);

  label75 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label75);
  gtk_box_pack_start (GTK_BOX (hbox18), label75, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) rbfbuttonconfirm, "clicked",
                    G_CALLBACK (rbfon_buttonconfirm_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfbuttonretour5, "clicked",
                    G_CALLBACK (rbfon_buttonretour5_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rbfwindow3, rbfwindow3, "rbfwindow3");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbffixed3, "rbffixed3");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfspinbutton123, "rbfspinbutton123");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfspinbutton223, "rbfspinbutton223");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfentry123, "rbfentry123");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfentry223, "rbfentry223");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfentry323, "rbfentry323");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfentry423, "rbfentry423");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel17, "rbflabel17");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel24, "rbflabel24");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel26, "rbflabel26");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel23, "rbflabel23");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel18, "rbflabel18");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel25, "rbflabel25");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel27, "rbflabel27");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel32, "rbflabel32");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfspinbutton323, "rbfspinbutton323");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel20, "rbflabel20");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel21, "rbflabel21");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel22, "rbflabel22");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbflabel19, "rbflabel19");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfcombobox4, "rbfcombobox4");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfcombobox5, "rbfcombobox5");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfcombobox6, "rbfcombobox6");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfbuttonconfirm, "rbfbuttonconfirm");
  GLADE_HOOKUP_OBJECT (rbfwindow3, rbfbuttonretour5, "rbfbuttonretour5");
  GLADE_HOOKUP_OBJECT (rbfwindow3, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (rbfwindow3, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (rbfwindow3, image18, "image18");
  GLADE_HOOKUP_OBJECT (rbfwindow3, label75, "label75");

  return rbfwindow3;
}

GtkWidget*
create_rbfwindow (void)
{
  GtkWidget *rbfwindow;
  GtkWidget *rbffixed4;
  GtkWidget *rbfajout;
  GtkWidget *rbfafficher;
  GtkWidget *rbfsupprimer;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label33;

  rbfwindow = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (rbfwindow, 350, 350);
  gtk_window_set_title (GTK_WINDOW (rbfwindow), _("window"));

  rbffixed4 = gtk_fixed_new ();
  gtk_widget_show (rbffixed4);
  gtk_container_add (GTK_CONTAINER (rbfwindow), rbffixed4);

  rbfajout = gtk_button_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (rbfajout);
  gtk_fixed_put (GTK_FIXED (rbffixed4), rbfajout, 96, 56);
  gtk_widget_set_size_request (rbfajout, 232, 80);

  rbfafficher = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (rbfafficher);
  gtk_fixed_put (GTK_FIXED (rbffixed4), rbfafficher, 96, 160);
  gtk_widget_set_size_request (rbfafficher, 232, 80);

  rbfsupprimer = gtk_button_new ();
  gtk_widget_show (rbfsupprimer);
  gtk_fixed_put (GTK_FIXED (rbffixed4), rbfsupprimer, 96, 264);
  gtk_widget_set_size_request (rbfsupprimer, 232, 88);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (rbfsupprimer), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label33 = gtk_label_new_with_mnemonic (_("Modifier/Supprimer"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox6), label33, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) rbfajout, "clicked",
                    G_CALLBACK (rbfon_ajout_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfafficher, "clicked",
                    G_CALLBACK (rbfon_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfsupprimer, "clicked",
                    G_CALLBACK (rbfon_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rbfwindow, rbfwindow, "rbfwindow");
  GLADE_HOOKUP_OBJECT (rbfwindow, rbffixed4, "rbffixed4");
  GLADE_HOOKUP_OBJECT (rbfwindow, rbfajout, "rbfajout");
  GLADE_HOOKUP_OBJECT (rbfwindow, rbfafficher, "rbfafficher");
  GLADE_HOOKUP_OBJECT (rbfwindow, rbfsupprimer, "rbfsupprimer");
  GLADE_HOOKUP_OBJECT (rbfwindow, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (rbfwindow, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (rbfwindow, image6, "image6");
  GLADE_HOOKUP_OBJECT (rbfwindow, label33, "label33");

  return rbfwindow;
}

GtkWidget*
create_rbfwindow4 (void)
{
  GtkWidget *rbfwindow4;
  GtkWidget *rbffixed5;
  GtkWidget *rbfentrysupmod;
  GtkWidget *rbflabel34;
  GtkWidget *rbfentrID;
  GtkWidget *rbferreur;
  GtkWidget *rbfmodifyvol1;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image14;
  GtkWidget *label71;
  GtkWidget *rbfretour1enterid;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image16;
  GtkWidget *label73;
  GtkWidget *rbfsupprr;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image15;
  GtkWidget *label72;

  rbfwindow4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (rbfwindow4), _("window4"));
  gtk_window_set_position (GTK_WINDOW (rbfwindow4), GTK_WIN_POS_CENTER_ALWAYS);
  gtk_window_set_default_size (GTK_WINDOW (rbfwindow4), 500, 500);

  rbffixed5 = gtk_fixed_new ();
  gtk_widget_show (rbffixed5);
  gtk_container_add (GTK_CONTAINER (rbfwindow4), rbffixed5);

  rbfentrysupmod = gtk_entry_new ();
  gtk_widget_show (rbfentrysupmod);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbfentrysupmod, 96, 88);
  gtk_widget_set_size_request (rbfentrysupmod, 280, 48);
  gtk_entry_set_invisible_char (GTK_ENTRY (rbfentrysupmod), 8226);

  rbflabel34 = gtk_label_new ("");
  gtk_widget_show (rbflabel34);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbflabel34, 168, 216);
  gtk_widget_set_size_request (rbflabel34, 60, 20);

  rbfentrID = gtk_label_new (_("Entrer ID du vol \303\240 modifier"));
  gtk_widget_show (rbfentrID);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbfentrID, 88, 32);
  gtk_widget_set_size_request (rbfentrID, 296, 32);

  rbferreur = gtk_label_new ("");
  gtk_widget_show (rbferreur);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbferreur, 192, 144);
  gtk_widget_set_size_request (rbferreur, 104, 25);

  rbfmodifyvol1 = gtk_button_new ();
  gtk_widget_show (rbfmodifyvol1);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbfmodifyvol1, 96, 184);
  gtk_widget_set_size_request (rbfmodifyvol1, 280, 88);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (rbfmodifyvol1), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image14 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image14);
  gtk_box_pack_start (GTK_BOX (hbox14), image14, FALSE, FALSE, 0);

  label71 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label71);
  gtk_box_pack_start (GTK_BOX (hbox14), label71, FALSE, FALSE, 0);

  rbfretour1enterid = gtk_button_new ();
  gtk_widget_show (rbfretour1enterid);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbfretour1enterid, 336, 424);
  gtk_widget_set_size_request (rbfretour1enterid, 132, 45);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (rbfretour1enterid), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image16 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox16), image16, FALSE, FALSE, 0);

  label73 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label73);
  gtk_box_pack_start (GTK_BOX (hbox16), label73, FALSE, FALSE, 0);

  rbfsupprr = gtk_button_new ();
  gtk_widget_show (rbfsupprr);
  gtk_fixed_put (GTK_FIXED (rbffixed5), rbfsupprr, 96, 296);
  gtk_widget_set_size_request (rbfsupprr, 280, 88);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (rbfsupprr), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image15 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox15), image15, FALSE, FALSE, 0);

  label72 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label72);
  gtk_box_pack_start (GTK_BOX (hbox15), label72, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) rbfmodifyvol1, "clicked",
                    G_CALLBACK (rbfon_modifyvol1_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfretour1enterid, "clicked",
                    G_CALLBACK (rbfon_retour1enterid_clicked),
                    NULL);
  g_signal_connect ((gpointer) rbfsupprr, "clicked",
                    G_CALLBACK (rbfon_supprr_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (rbfwindow4, rbfwindow4, "rbfwindow4");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbffixed5, "rbffixed5");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbfentrysupmod, "rbfentrysupmod");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbflabel34, "rbflabel34");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbfentrID, "rbfentrID");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbferreur, "rbferreur");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbfmodifyvol1, "rbfmodifyvol1");
  GLADE_HOOKUP_OBJECT (rbfwindow4, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (rbfwindow4, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (rbfwindow4, image14, "image14");
  GLADE_HOOKUP_OBJECT (rbfwindow4, label71, "label71");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbfretour1enterid, "rbfretour1enterid");
  GLADE_HOOKUP_OBJECT (rbfwindow4, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (rbfwindow4, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (rbfwindow4, image16, "image16");
  GLADE_HOOKUP_OBJECT (rbfwindow4, label73, "label73");
  GLADE_HOOKUP_OBJECT (rbfwindow4, rbfsupprr, "rbfsupprr");
  GLADE_HOOKUP_OBJECT (rbfwindow4, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (rbfwindow4, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (rbfwindow4, image15, "image15");
  GLADE_HOOKUP_OBJECT (rbfwindow4, label72, "label72");

  return rbfwindow4;
}
///////////////////////////kamel//////////////////////////

GtkWidget*
create_tbwindow1 (void)
{
  GtkWidget *tbwindow1;
  GtkWidget *tbfixed1;
  GtkObject *tbspinbutton1_adj;
  GtkWidget *tbspinbutton1;
  GtkObject *tbspinbutton3_adj;
  GtkWidget *tbspinbutton3;
  GtkWidget *tbentryi;
  GtkWidget *tbentry1998;
  GtkWidget *tbentry2005;
  GtkWidget *tbentry2006;
  GtkWidget *tbentry2007;
  GtkWidget *tbentry2008;
  GtkWidget *tbentry2009;
  GtkWidget *tbentry2010;
  GtkWidget *tbimage6;
  GtkWidget *tbcomboboxh;
  GtkWidget *tblabelh;
  GtkWidget *tblabelekm;
  GtkWidget *tblabelp;
  GtkWidget *tblabeli;
  GtkWidget *tblabelr;
  GtkWidget *tbbuttonrch;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label7;
  GtkWidget *tblabelhkm;
  GtkWidget *tblabelvkm;
  GtkWidget *tblabele;
  GtkWidget *tblabelpkm;
  GtkWidget *tblabelikm;
  GtkWidget *tblabelmkm;
  GtkWidget *tbajouter_v;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *tbimage1;
  GtkWidget *tblabel1;
  GtkWidget *tbafficher_v;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label3;
  GtkWidget *tbmodifier_v;
  GtkWidget *alignment4;
  GtkWidget *tbhbox4;
  GtkWidget *tbimage4;
  GtkWidget *tblabel4;
  GtkWidget *tbimage_principale_919b9d_png;
  GtkWidget *tbcomboboxe;
  GtkWidget *tblabel9km;
  GtkWidget *tblabelv;
  GtkWidget *tblabel_7;
  GtkWidget *tbcomboboxv;

  tbwindow1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_widget_set_size_request (tbwindow1, 1280, -1);
  gtk_window_set_title (GTK_WINDOW (tbwindow1), _("espace agent"));

  tbfixed1 = gtk_fixed_new ();
  gtk_widget_show (tbfixed1);
  gtk_container_add (GTK_CONTAINER (tbwindow1), tbfixed1);

  tbspinbutton1_adj = gtk_adjustment_new (10, 10, 900, 1, 10, 10);
  tbspinbutton1 = gtk_spin_button_new (GTK_ADJUSTMENT (tbspinbutton1_adj), 1, 0);
  gtk_widget_show (tbspinbutton1);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbspinbutton1, 896, 64);
  gtk_widget_set_size_request (tbspinbutton1, 80, 32);

  tbspinbutton3_adj = gtk_adjustment_new (1, 10, 1000, 1, 10, 10);
  tbspinbutton3 = gtk_spin_button_new (GTK_ADJUSTMENT (tbspinbutton3_adj), 1, 0);
  gtk_widget_show (tbspinbutton3);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbspinbutton3, 1152, 64);
  gtk_widget_set_size_request (tbspinbutton3, 112, 32);

  tbentryi = gtk_entry_new ();
  gtk_widget_show (tbentryi);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentryi, 1024, 64);
  gtk_widget_set_size_request (tbentryi, 80, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentryi), 8226);

  tbentry1998 = gtk_entry_new ();
  gtk_widget_show (tbentry1998);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry1998, 784, 136);
  gtk_widget_set_size_request (tbentry1998, 72, 32);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry1998), 8226);

  tbentry2005 = gtk_entry_new ();
  gtk_widget_show (tbentry2005);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry2005, 696, 240);
  gtk_widget_set_size_request (tbentry2005, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry2005), 8226);

  tbentry2006 = gtk_entry_new ();
  gtk_widget_show (tbentry2006);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry2006, 696, 192);
  gtk_widget_set_size_request (tbentry2006, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry2006), 8226);

  tbentry2007 = gtk_entry_new ();
  gtk_widget_show (tbentry2007);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry2007, 696, 288);
  gtk_widget_set_size_request (tbentry2007, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry2007), 8226);

  tbentry2008 = gtk_entry_new ();
  gtk_widget_show (tbentry2008);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry2008, 696, 344);
  gtk_widget_set_size_request (tbentry2008, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry2008), 8226);

  tbentry2009 = gtk_entry_new ();
  gtk_widget_show (tbentry2009);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry2009, 696, 392);
  gtk_widget_set_size_request (tbentry2009, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry2009), 8226);

  tbentry2010 = gtk_entry_new ();
  gtk_widget_show (tbentry2010);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbentry2010, 696, 432);
  gtk_widget_set_size_request (tbentry2010, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (tbentry2010), 8226);

  tbimage6 = create_pixmap (tbwindow1, "arriere plan.jpg");
  gtk_widget_show (tbimage6);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbimage6, 304, 0);
  gtk_widget_set_size_request (tbimage6, 992, 472);

  tbcomboboxh = gtk_combo_box_new_text ();
  gtk_widget_show (tbcomboboxh);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbcomboboxh, 312, 64);
  gtk_widget_set_size_request (tbcomboboxh, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), "");
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("J E R B A:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Badira"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Magic"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Saida"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Cigale"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("T O U Z E R:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Khella"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Marigold"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Hasdrubal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("T U N I S:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Ibis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Movenpick"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Tour"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Concorde"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("S O U S S E:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Laico"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Robinson"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Royal"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("H A M M A M E T:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Mouradi"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Palace"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("Haway"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("G A M M A R T H:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("fido"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("gikow"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("nihaw"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("vikil"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("M O N  A S T I R:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("gikabo "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("bijiha"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("anaci"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("M A H D I A:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("gijit"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("vohur"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("nytor"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("M I D O U N:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("quive"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("nikonk"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("hyter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("N A B E U L:"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("qyter"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("jiton"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("bines"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxh), _("gitow"));

  tblabelh = gtk_label_new (_("hotel"));
  gtk_widget_show (tblabelh);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelh, 312, 16);
  gtk_widget_set_size_request (tblabelh, 80, 32);

  tblabelekm = gtk_label_new (_("etoile"));
  gtk_widget_show (tblabelekm);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelekm, 704, 8);
  gtk_widget_set_size_request (tblabelekm, 64, 40);

  tblabelp = gtk_label_new (_("prix"));
  gtk_widget_show (tblabelp);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelp, 888, 16);
  gtk_widget_set_size_request (tblabelp, 72, 32);

  tblabeli = gtk_label_new (_("id"));
  gtk_widget_show (tblabeli);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabeli, 1008, 16);
  gtk_widget_set_size_request (tblabeli, 88, 32);

  tblabelr = gtk_label_new (_("max reservation"));
  gtk_widget_show (tblabelr);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelr, 1144, 16);
  gtk_widget_set_size_request (tblabelr, 136, 40);

  tbbuttonrch = gtk_button_new ();
  gtk_widget_show (tbbuttonrch);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbbuttonrch, 648, 136);
  gtk_widget_set_size_request (tbbuttonrch, 136, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (tbbuttonrch), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox5), label7, FALSE, FALSE, 0);

  tblabelhkm = gtk_label_new (_("hotel"));
  gtk_widget_show (tblabelhkm);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelhkm, 616, 184);
  gtk_widget_set_size_request (tblabelhkm, 64, 40);

  tblabelvkm = gtk_label_new (_("ville"));
  gtk_widget_show (tblabelvkm);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelvkm, 600, 232);
  gtk_widget_set_size_request (tblabelvkm, 89, 40);

  tblabele = gtk_label_new (_("etoile"));
  gtk_widget_show (tblabele);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabele, 616, 280);
  gtk_widget_set_size_request (tblabele, 80, 32);

  tblabelpkm = gtk_label_new (_("prix"));
  gtk_widget_show (tblabelpkm);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelpkm, 624, 336);
  gtk_widget_set_size_request (tblabelpkm, 64, 32);

  tblabelikm = gtk_label_new (_("id"));
  gtk_widget_show (tblabelikm);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelikm, 624, 384);
  gtk_widget_set_size_request (tblabelikm, 64, 40);

  tblabelmkm = gtk_label_new (_("max reservation"));
  gtk_widget_show (tblabelmkm);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelmkm, 568, 424);
  gtk_widget_set_size_request (tblabelmkm, 120, 48);

  tbajouter_v = gtk_button_new ();
  gtk_widget_show (tbajouter_v);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbajouter_v, 1048, 200);
  gtk_widget_set_size_request (tbajouter_v, 104, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (tbajouter_v), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  tbimage1 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (tbimage1);
  gtk_box_pack_start (GTK_BOX (hbox1), tbimage1, FALSE, FALSE, 0);

  tblabel1 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (tblabel1);
  gtk_box_pack_start (GTK_BOX (hbox1), tblabel1, FALSE, FALSE, 0);

  tbafficher_v = gtk_button_new ();
  gtk_widget_show (tbafficher_v);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbafficher_v, 1048, 352);
  gtk_widget_set_size_request (tbafficher_v, 104, 40);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (tbafficher_v), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("afficher"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox3), label3, FALSE, FALSE, 0);

  tbmodifier_v = gtk_button_new ();
  gtk_widget_show (tbmodifier_v);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbmodifier_v, 1048, 280);
  gtk_widget_set_size_request (tbmodifier_v, 104, 40);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (tbmodifier_v), alignment4);

  tbhbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (tbhbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), tbhbox4);

  tbimage4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (tbimage4);
  gtk_box_pack_start (GTK_BOX (tbhbox4), tbimage4, FALSE, FALSE, 0);

  tblabel4 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (tblabel4);
  gtk_box_pack_start (GTK_BOX (tbhbox4), tblabel4, FALSE, FALSE, 0);

  tbimage_principale_919b9d_png = create_pixmap (tbwindow1, "image-principale-919b9d.png");
  gtk_widget_show (tbimage_principale_919b9d_png);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbimage_principale_919b9d_png, 8, 0);
  gtk_widget_set_size_request (tbimage_principale_919b9d_png, 296, 472);
  GTK_WIDGET_SET_FLAGS (tbimage_principale_919b9d_png, GTK_CAN_FOCUS);

  tbcomboboxe = gtk_combo_box_new_text ();
  gtk_widget_show (tbcomboboxe);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbcomboboxe, 704, 64);
  gtk_widget_set_size_request (tbcomboboxe, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxe), _("5"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxe), _("4"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxe), _("3"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxe), _("2"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxe), _("1"));

  tblabel9km = gtk_label_new ("");
  gtk_widget_show (tblabel9km);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabel9km, 928, 120);
  gtk_widget_set_size_request (tblabel9km, 280, 40);

  tblabelv = gtk_label_new (_("ville"));
  gtk_widget_show (tblabelv);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabelv, 488, 8);
  gtk_widget_set_size_request (tblabelv, 88, 40);

  tblabel_7 = gtk_label_new ("");
  gtk_widget_show (tblabel_7);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tblabel_7, 944, 408);
  gtk_widget_set_size_request (tblabel_7, 320, 40);

  tbcomboboxv = gtk_combo_box_new_text ();
  gtk_widget_show (tbcomboboxv);
  gtk_fixed_put (GTK_FIXED (tbfixed1), tbcomboboxv, 512, 64);
  gtk_widget_set_size_request (tbcomboboxv, 150, 35);
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Jerba"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Touzer"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Tunis"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Sousse"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Hammamet"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Gammarth"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Monastir"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Mahdia"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Midoun"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (tbcomboboxv), _("Nabeul"));

  g_signal_connect ((gpointer) tbbuttonrch, "clicked",
                    G_CALLBACK (tbon_buttonrch_clicked),
                    NULL);
  g_signal_connect ((gpointer) tbajouter_v, "clicked",
                    G_CALLBACK (tbon_ajouter_v_clicked),
                    NULL);
  g_signal_connect ((gpointer) tbafficher_v, "clicked",
                    G_CALLBACK (tbon_afficher_v_clicked),
                    NULL);
  g_signal_connect ((gpointer) tbmodifier_v, "clicked",
                    G_CALLBACK (tbon_modifier_v_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tbwindow1, tbwindow1, "tbwindow1");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbfixed1, "tbfixed1");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbspinbutton1, "tbspinbutton1");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbspinbutton3, "tbspinbutton3");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentryi, "tbentryi");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry1998, "tbentry1998");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry2005, "tbentry2005");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry2006, "tbentry2006");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry2007, "tbentry2007");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry2008, "tbentry2008");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry2009, "tbentry2009");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbentry2010, "tbentry2010");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbimage6, "tbimage6");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbcomboboxh, "tbcomboboxh");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelh, "tblabelh");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelekm, "tblabelekm");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelp, "tblabelp");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabeli, "tblabeli");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelr, "tblabelr");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbbuttonrch, "tbbuttonrch");
  GLADE_HOOKUP_OBJECT (tbwindow1, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (tbwindow1, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (tbwindow1, image5, "image5");
  GLADE_HOOKUP_OBJECT (tbwindow1, label7, "label7");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelhkm, "tblabelhkm");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelvkm, "tblabelvkm");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabele, "tblabele");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelpkm, "tblabelpkm");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelikm, "tblabelikm");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelmkm, "tblabelmkm");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbajouter_v, "tbajouter_v");
  GLADE_HOOKUP_OBJECT (tbwindow1, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (tbwindow1, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbimage1, "tbimage1");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabel1, "tblabel1");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbafficher_v, "tbafficher_v");
  GLADE_HOOKUP_OBJECT (tbwindow1, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (tbwindow1, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (tbwindow1, image3, "image3");
  GLADE_HOOKUP_OBJECT (tbwindow1, label3, "label3");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbmodifier_v, "tbmodifier_v");
  GLADE_HOOKUP_OBJECT (tbwindow1, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbhbox4, "tbhbox4");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbimage4, "tbimage4");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabel4, "tblabel4");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbimage_principale_919b9d_png, "tbimage_principale_919b9d_png");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbcomboboxe, "tbcomboboxe");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabel9km, "tblabel9km");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabelv, "tblabelv");
  GLADE_HOOKUP_OBJECT (tbwindow1, tblabel_7, "tblabel_7");
  GLADE_HOOKUP_OBJECT (tbwindow1, tbcomboboxv, "tbcomboboxv");

  gtk_widget_grab_focus (tbimage_principale_919b9d_png);
  gtk_widget_grab_default (tbimage_principale_919b9d_png);
  return tbwindow1;
}

GtkWidget*
create_tbwindow2 (void)
{
  GtkWidget *tbwindow2;
  GtkWidget *tbfixed2;
  GtkWidget *tbtreeview1;
  GtkWidget *tblabel8km;
  GtkWidget *tbimage7;
  GtkWidget *tbbutton_supprimer;
  GtkWidget *tbretour;

  tbwindow2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (tbwindow2), _("list hebergement"));

  tbfixed2 = gtk_fixed_new ();
  gtk_widget_show (tbfixed2);
  gtk_container_add (GTK_CONTAINER (tbwindow2), tbfixed2);

  tbtreeview1 = gtk_tree_view_new ();
  gtk_widget_show (tbtreeview1);
  gtk_fixed_put (GTK_FIXED (tbfixed2), tbtreeview1, 152, 112);
  gtk_widget_set_size_request (tbtreeview1, 952, 416);

  tblabel8km = gtk_label_new ("");
  gtk_widget_show (tblabel8km);
  gtk_fixed_put (GTK_FIXED (tbfixed2), tblabel8km, 680, 56);
  gtk_widget_set_size_request (tblabel8km, 272, 40);

  tbimage7 = create_pixmap (tbwindow2, "arriere plan.jpg");
  gtk_widget_show (tbimage7);
  gtk_fixed_put (GTK_FIXED (tbfixed2), tbimage7, 0, 8);
  gtk_widget_set_size_request (tbimage7, 1280, 544);

  tbbutton_supprimer = gtk_button_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (tbbutton_supprimer);
  gtk_fixed_put (GTK_FIXED (tbfixed2), tbbutton_supprimer, 912, 48);
  gtk_widget_set_size_request (tbbutton_supprimer, 120, 40);

  tbretour = gtk_button_new_from_stock ("retour");
  gtk_widget_show (tbretour);
  gtk_fixed_put (GTK_FIXED (tbfixed2), tbretour, 168, 48);
  gtk_widget_set_size_request (tbretour, 112, 40);

  g_signal_connect ((gpointer) tbbutton_supprimer, "clicked",
                    G_CALLBACK (tbon_button_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) tbretour, "clicked",
                    G_CALLBACK (tbon_retour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (tbwindow2, tbwindow2, "tbwindow2");
  GLADE_HOOKUP_OBJECT (tbwindow2, tbfixed2, "tbfixed2");
  GLADE_HOOKUP_OBJECT (tbwindow2, tbtreeview1, "tbtreeview1");
  GLADE_HOOKUP_OBJECT (tbwindow2, tblabel8km, "tblabel8km");
  GLADE_HOOKUP_OBJECT (tbwindow2, tbimage7, "tbimage7");
  GLADE_HOOKUP_OBJECT (tbwindow2, tbbutton_supprimer, "tbbutton_supprimer");
  GLADE_HOOKUP_OBJECT (tbwindow2, tbretour, "tbretour");

  return tbwindow2;
}
 


  
