/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */
///////abdou/////
GtkWidget* create_abdouwindow1 (void);
GtkWidget* create_abdouwindow2 (void);
GtkWidget* create_abdouwindow3 (void);
GtkWidget* create_abdouwindow4 (void);
GtkWidget* create_abdouwindow5 (void);
GtkWidget* create_abdouwindow6 (void);
//////////////rana///////////
GtkWidget* create_rbfwindow1 (void);
GtkWidget* create_rbfwindowaffichage (void);
GtkWidget* create_rbfwindow3 (void);
GtkWidget* create_rbfwindow (void);
GtkWidget* create_rbfwindow4 (void);
///////////kaneml////////////
GtkWidget* create_tbwindow1 (void);
GtkWidget* create_tbwindow2 (void);
