/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_cmfenetre_ajout (void)
{
  GtkWidget *cmfenetre_ajout;
  GtkWidget *fixed1;
  GtkWidget *cmnom;
  GtkWidget *cmdate;
  GtkWidget *cmcin;
  GtkWidget *cmid;
  GtkWidget *cmprenom;
  GtkWidget *label7;
  GtkWidget *label8;
  GtkWidget *label9;
  GtkWidget *label10;
  GtkWidget *label13;
  GtkWidget *label11;
  GtkWidget *label12;
  GtkWidget *cmcombobox1;
  GtkWidget *cmajouter;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label31;
  GtkWidget *cmafficher;
  GtkWidget *cmbutton2;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image10;
  GtkWidget *label32;

  cmfenetre_ajout = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cmfenetre_ajout), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (cmfenetre_ajout), fixed1);

  cmnom = gtk_entry_new ();
  gtk_widget_show (cmnom);
  gtk_fixed_put (GTK_FIXED (fixed1), cmnom, 128, 88);
  gtk_widget_set_size_request (cmnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmnom), 8226);

  cmdate = gtk_entry_new ();
  gtk_widget_show (cmdate);
  gtk_fixed_put (GTK_FIXED (fixed1), cmdate, 464, 88);
  gtk_widget_set_size_request (cmdate, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmdate), 8226);

  cmcin = gtk_entry_new ();
  gtk_widget_show (cmcin);
  gtk_fixed_put (GTK_FIXED (fixed1), cmcin, 456, 128);
  gtk_widget_set_size_request (cmcin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmcin), 8226);

  cmid = gtk_entry_new ();
  gtk_widget_show (cmid);
  gtk_fixed_put (GTK_FIXED (fixed1), cmid, 440, 168);
  gtk_widget_set_size_request (cmid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmid), 8226);

  cmprenom = gtk_entry_new ();
  gtk_widget_show (cmprenom);
  gtk_fixed_put (GTK_FIXED (fixed1), cmprenom, 128, 120);
  gtk_widget_set_size_request (cmprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmprenom), 8226);

  label7 = gtk_label_new (_("ajout d ' un agent"));
  gtk_widget_show (label7);
  gtk_fixed_put (GTK_FIXED (fixed1), label7, 208, 40);
  gtk_widget_set_size_request (label7, 168, 16);

  label8 = gtk_label_new (_("Nom"));
  gtk_widget_show (label8);
  gtk_fixed_put (GTK_FIXED (fixed1), label8, 24, 80);
  gtk_widget_set_size_request (label8, 112, 48);

  label9 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label9);
  gtk_fixed_put (GTK_FIXED (fixed1), label9, 8, 120);
  gtk_widget_set_size_request (label9, 152, 32);

  label10 = gtk_label_new (_("Domaine"));
  gtk_widget_show (label10);
  gtk_fixed_put (GTK_FIXED (fixed1), label10, 40, 168);
  gtk_widget_set_size_request (label10, 104, 16);

  label13 = gtk_label_new (_("ID"));
  gtk_widget_show (label13);
  gtk_fixed_put (GTK_FIXED (fixed1), label13, 368, 176);
  gtk_widget_set_size_request (label13, 49, 17);

  label11 = gtk_label_new (_("CIN"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed1), label11, 368, 128);
  gtk_widget_set_size_request (label11, 49, 17);

  label12 = gtk_label_new (_("Date de recrut"));
  gtk_widget_show (label12);
  gtk_fixed_put (GTK_FIXED (fixed1), label12, 312, 96);
  gtk_widget_set_size_request (label12, 152, 24);

  cmcombobox1 = gtk_combo_box_new_text ();
  gtk_widget_show (cmcombobox1);
  gtk_fixed_put (GTK_FIXED (fixed1), cmcombobox1, 144, 160);
  gtk_widget_set_size_request (cmcombobox1, 104, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cmcombobox1), _("financier "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cmcombobox1), _("securite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cmcombobox1), _("prestataire"));

  cmajouter = gtk_button_new ();
  gtk_widget_show (cmajouter);
  gtk_fixed_put (GTK_FIXED (fixed1), cmajouter, 216, 232);
  gtk_widget_set_size_request (cmajouter, 68, 29);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (cmajouter), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label31 = gtk_label_new_with_mnemonic (_("Ajouter"));
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox9), label31, FALSE, FALSE, 0);

  cmafficher = gtk_button_new_with_mnemonic (_("Afficher"));
  gtk_widget_show (cmafficher);
  gtk_fixed_put (GTK_FIXED (fixed1), cmafficher, 320, 232);
  gtk_widget_set_size_request (cmafficher, 68, 29);

  cmbutton2 = gtk_button_new ();
  gtk_widget_show (cmbutton2);
  gtk_fixed_put (GTK_FIXED (fixed1), cmbutton2, 16, 16);
  gtk_widget_set_size_request (cmbutton2, 68, 29);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (cmbutton2), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image10 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_box_pack_start (GTK_BOX (hbox10), image10, FALSE, FALSE, 0);

  label32 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label32);
  gtk_box_pack_start (GTK_BOX (hbox10), label32, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) cmajouter, "clicked",
                    G_CALLBACK (cmon_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) cmafficher, "clicked",
                    G_CALLBACK (cmon_afficher_clicked),
                    NULL);
  g_signal_connect ((gpointer) cmbutton2, "clicked",
                    G_CALLBACK (on_cmbutton2_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cmfenetre_ajout, cmfenetre_ajout, "cmfenetre_ajout");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmnom, "cmnom");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmdate, "cmdate");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmcin, "cmcin");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmid, "cmid");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmprenom, "cmprenom");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label7, "label7");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label8, "label8");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label9, "label9");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label10, "label10");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label13, "label13");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label11, "label11");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label12, "label12");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmcombobox1, "cmcombobox1");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmajouter, "cmajouter");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, image9, "image9");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label31, "label31");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmafficher, "cmafficher");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, cmbutton2, "cmbutton2");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, image10, "image10");
  GLADE_HOOKUP_OBJECT (cmfenetre_ajout, label32, "label32");

  return cmfenetre_ajout;
}

GtkWidget*
create_cmfenetre_afficher (void)
{
  GtkWidget *cmfenetre_afficher;
  GtkWidget *fixed2;
  GtkWidget *cmtreeview1;
  GtkWidget *label14;
  GtkWidget *cmretour;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label25;
  GtkWidget *cmmodifier;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label27;
  GtkWidget *cmsupprimer;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label26;

  cmfenetre_afficher = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cmfenetre_afficher), _("window2"));
  gtk_window_set_default_size (GTK_WINDOW (cmfenetre_afficher), 1200, 1000);

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (cmfenetre_afficher), fixed2);

  cmtreeview1 = gtk_tree_view_new ();
  gtk_widget_show (cmtreeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), cmtreeview1, 32, 56);
  gtk_widget_set_size_request (cmtreeview1, 920, 160);

  label14 = gtk_label_new (_("afficher la liste des agents"));
  gtk_widget_show (label14);
  gtk_fixed_put (GTK_FIXED (fixed2), label14, 104, 24);
  gtk_widget_set_size_request (label14, 208, 16);

  cmretour = gtk_button_new ();
  gtk_widget_show (cmretour);
  gtk_fixed_put (GTK_FIXED (fixed2), cmretour, 0, 0);
  gtk_widget_set_size_request (cmretour, 80, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (cmretour), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label25 = gtk_label_new_with_mnemonic (_("Retour"));
  gtk_widget_show (label25);
  gtk_box_pack_start (GTK_BOX (hbox3), label25, FALSE, FALSE, 0);

  cmmodifier = gtk_button_new ();
  gtk_widget_show (cmmodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), cmmodifier, 248, 296);
  gtk_widget_set_size_request (cmmodifier, 112, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (cmmodifier), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label27 = gtk_label_new_with_mnemonic (_("Modifier"));
  gtk_widget_show (label27);
  gtk_box_pack_start (GTK_BOX (hbox5), label27, FALSE, FALSE, 0);

  cmsupprimer = gtk_button_new ();
  gtk_widget_show (cmsupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), cmsupprimer, 80, 296);
  gtk_widget_set_size_request (cmsupprimer, 128, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (cmsupprimer), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label26 = gtk_label_new_with_mnemonic (_("Supprimer"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox4), label26, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) cmretour, "clicked",
                    G_CALLBACK (cmon_retour_clicked),
                    NULL);
  g_signal_connect ((gpointer) cmmodifier, "clicked",
                    G_CALLBACK (cmon_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) cmsupprimer, "clicked",
                    G_CALLBACK (cmon_supprimer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cmfenetre_afficher, cmfenetre_afficher, "cmfenetre_afficher");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, cmtreeview1, "cmtreeview1");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, label14, "label14");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, cmretour, "cmretour");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, image3, "image3");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, label25, "label25");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, cmmodifier, "cmmodifier");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, image5, "image5");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, label27, "label27");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, cmsupprimer, "cmsupprimer");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, image4, "image4");
  GLADE_HOOKUP_OBJECT (cmfenetre_afficher, label26, "label26");

  return cmfenetre_afficher;
}

GtkWidget*
create_cmwindow3 (void)
{
  GtkWidget *cmwindow3;
  GtkWidget *fixed3;
  GtkWidget *cmbutton8;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label29;
  GtkWidget *fixed4;
  GtkWidget *label16;
  GtkWidget *label17;
  GtkWidget *cmnnom;
  GtkWidget *cmndate;
  GtkWidget *cmncin;
  GtkWidget *cmnid;
  GtkWidget *cmnprenom;
  GtkWidget *label19;
  GtkWidget *label21;
  GtkWidget *label15;
  GtkWidget *label18;
  GtkWidget *label20;
  GtkWidget *cmcombobox2;
  GtkWidget *cmbutton7;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label28;

  cmwindow3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cmwindow3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (cmwindow3), fixed3);

  cmbutton8 = gtk_button_new ();
  gtk_widget_show (cmbutton8);
  gtk_fixed_put (GTK_FIXED (fixed3), cmbutton8, 48, 32);
  gtk_widget_set_size_request (cmbutton8, 80, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (cmbutton8), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label29 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox7), label29, FALSE, FALSE, 0);

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_fixed_put (GTK_FIXED (fixed3), fixed4, 80, 64);
  gtk_widget_set_size_request (fixed4, 0, 0);

  label16 = gtk_label_new (_("CIN"));
  gtk_widget_show (label16);
  gtk_fixed_put (GTK_FIXED (fixed4), label16, 368, 128);
  gtk_widget_set_size_request (label16, 49, 17);

  label17 = gtk_label_new (_("Date de recrut"));
  gtk_widget_show (label17);
  gtk_fixed_put (GTK_FIXED (fixed4), label17, 312, 96);
  gtk_widget_set_size_request (label17, 152, 24);

  cmnnom = gtk_entry_new ();
  gtk_widget_show (cmnnom);
  gtk_fixed_put (GTK_FIXED (fixed4), cmnnom, 120, 88);
  gtk_widget_set_size_request (cmnnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmnnom), 8226);

  cmndate = gtk_entry_new ();
  gtk_widget_show (cmndate);
  gtk_fixed_put (GTK_FIXED (fixed4), cmndate, 464, 88);
  gtk_widget_set_size_request (cmndate, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmndate), 8226);

  cmncin = gtk_entry_new ();
  gtk_widget_show (cmncin);
  gtk_fixed_put (GTK_FIXED (fixed4), cmncin, 456, 128);
  gtk_widget_set_size_request (cmncin, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmncin), 8226);

  cmnid = gtk_entry_new ();
  gtk_widget_show (cmnid);
  gtk_fixed_put (GTK_FIXED (fixed4), cmnid, 128, 56);
  gtk_widget_set_size_request (cmnid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmnid), 8226);

  cmnprenom = gtk_entry_new ();
  gtk_widget_show (cmnprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), cmnprenom, 128, 120);
  gtk_widget_set_size_request (cmnprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (cmnprenom), 8226);

  label19 = gtk_label_new (_("Nom"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (fixed4), label19, 24, 80);
  gtk_widget_set_size_request (label19, 112, 48);

  label21 = gtk_label_new (_("Prenom"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed4), label21, 8, 120);
  gtk_widget_set_size_request (label21, 152, 32);

  label15 = gtk_label_new (_("modifier le compte de l 'agent"));
  gtk_widget_show (label15);
  gtk_fixed_put (GTK_FIXED (fixed4), label15, 200, 24);
  gtk_widget_set_size_request (label15, 280, 16);

  label18 = gtk_label_new (_("ID"));
  gtk_widget_show (label18);
  gtk_fixed_put (GTK_FIXED (fixed4), label18, 64, 64);
  gtk_widget_set_size_request (label18, 49, 17);

  label20 = gtk_label_new (_("Domaine"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed4), label20, 40, 168);
  gtk_widget_set_size_request (label20, 104, 16);

  cmcombobox2 = gtk_combo_box_new_text ();
  gtk_widget_show (cmcombobox2);
  gtk_fixed_put (GTK_FIXED (fixed4), cmcombobox2, 144, 160);
  gtk_widget_set_size_request (cmcombobox2, 104, 32);
  gtk_combo_box_append_text (GTK_COMBO_BOX (cmcombobox2), _("financier "));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cmcombobox2), _("securite"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (cmcombobox2), _("prestataire"));

  cmbutton7 = gtk_button_new ();
  gtk_widget_show (cmbutton7);
  gtk_fixed_put (GTK_FIXED (fixed4), cmbutton7, 320, 232);
  gtk_widget_set_size_request (cmbutton7, 88, 29);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (cmbutton7), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label28 = gtk_label_new_with_mnemonic (_("valider"));
  gtk_widget_show (label28);
  gtk_box_pack_start (GTK_BOX (hbox6), label28, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) cmbutton8, "clicked",
                    G_CALLBACK (cmon_button8_clicked),
                    NULL);
  g_signal_connect ((gpointer) cmbutton7, "clicked",
                    G_CALLBACK (cmon_button7_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cmwindow3, cmwindow3, "cmwindow3");
  GLADE_HOOKUP_OBJECT (cmwindow3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmbutton8, "cmbutton8");
  GLADE_HOOKUP_OBJECT (cmwindow3, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (cmwindow3, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (cmwindow3, image7, "image7");
  GLADE_HOOKUP_OBJECT (cmwindow3, label29, "label29");
  GLADE_HOOKUP_OBJECT (cmwindow3, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (cmwindow3, label16, "label16");
  GLADE_HOOKUP_OBJECT (cmwindow3, label17, "label17");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmnnom, "cmnnom");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmndate, "cmndate");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmncin, "cmncin");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmnid, "cmnid");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmnprenom, "cmnprenom");
  GLADE_HOOKUP_OBJECT (cmwindow3, label19, "label19");
  GLADE_HOOKUP_OBJECT (cmwindow3, label21, "label21");
  GLADE_HOOKUP_OBJECT (cmwindow3, label15, "label15");
  GLADE_HOOKUP_OBJECT (cmwindow3, label18, "label18");
  GLADE_HOOKUP_OBJECT (cmwindow3, label20, "label20");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmcombobox2, "cmcombobox2");
  GLADE_HOOKUP_OBJECT (cmwindow3, cmbutton7, "cmbutton7");
  GLADE_HOOKUP_OBJECT (cmwindow3, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (cmwindow3, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (cmwindow3, image6, "image6");
  GLADE_HOOKUP_OBJECT (cmwindow3, label28, "label28");

  return cmwindow3;
}

GtkWidget*
create_cmwindow4 (void)
{
  GtkWidget *cmwindow4;
  GtkWidget *fixed5;
  GtkWidget *label11;
  GtkWidget *cmbutton9;
  GtkWidget *cmbutton10;

  cmwindow4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (cmwindow4), _("window4"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (cmwindow4), fixed5);

  label11 = gtk_label_new (_("compte admin"));
  gtk_widget_show (label11);
  gtk_fixed_put (GTK_FIXED (fixed5), label11, 112, 24);
  gtk_widget_set_size_request (label11, 152, 48);

  cmbutton9 = gtk_button_new_with_mnemonic (_("gestion des agents"));
  gtk_widget_show (cmbutton9);
  gtk_fixed_put (GTK_FIXED (fixed5), cmbutton9, 104, 96);
  gtk_widget_set_size_request (cmbutton9, 168, 64);

  cmbutton10 = gtk_button_new_with_mnemonic (_("gestion des clients"));
  gtk_widget_show (cmbutton10);
  gtk_fixed_put (GTK_FIXED (fixed5), cmbutton10, 104, 168);
  gtk_widget_set_size_request (cmbutton10, 168, 64);

  g_signal_connect ((gpointer) cmbutton9, "clicked",
                    G_CALLBACK (cmon_button9_clicked),
                    NULL);
  g_signal_connect ((gpointer) cmbutton10, "clicked",
                    G_CALLBACK (cmon_button10_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (cmwindow4, cmwindow4, "cmwindow4");
  GLADE_HOOKUP_OBJECT (cmwindow4, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (cmwindow4, label11, "label11");
  GLADE_HOOKUP_OBJECT (cmwindow4, cmbutton9, "cmbutton9");
  GLADE_HOOKUP_OBJECT (cmwindow4, cmbutton10, "cmbutton10");

  return cmwindow4;
}

GtkWidget*
create_chwindowsup (void)
{
  GtkWidget *chwindowsup;
  GtkWidget *fixed6;
  GtkWidget *chtreeview11;
  GtkWidget *label22;
  GtkWidget *chbutret;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label24;
  GtkWidget *chbutsup;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label23;

  chwindowsup = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (chwindowsup), _("window1"));
  gtk_window_set_default_size (GTK_WINDOW (chwindowsup), 1200, 1000);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (chwindowsup), fixed6);

  chtreeview11 = gtk_tree_view_new ();
  gtk_widget_show (chtreeview11);
  gtk_fixed_put (GTK_FIXED (fixed6), chtreeview11, 96, 56);
  gtk_widget_set_size_request (chtreeview11, 888, 200);

  label22 = gtk_label_new (_("afficher les listes des clients"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed6), label22, 120, 8);
  gtk_widget_set_size_request (label22, 248, 47);

  chbutret = gtk_button_new ();
  gtk_widget_show (chbutret);
  gtk_fixed_put (GTK_FIXED (fixed6), chbutret, 24, 16);
  gtk_widget_set_size_request (chbutret, 88, 32);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (chbutret), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label24 = gtk_label_new_with_mnemonic (_("retour"));
  gtk_widget_show (label24);
  gtk_box_pack_start (GTK_BOX (hbox2), label24, FALSE, FALSE, 0);

  chbutsup = gtk_button_new ();
  gtk_widget_show (chbutsup);
  gtk_fixed_put (GTK_FIXED (fixed6), chbutsup, 128, 280);
  gtk_widget_set_size_request (chbutsup, 152, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (chbutsup), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label23 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label23);
  gtk_box_pack_start (GTK_BOX (hbox1), label23, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) chbutret, "clicked",
                    G_CALLBACK (on_chbutret_clicked),
                    NULL);
  g_signal_connect ((gpointer) chbutsup, "clicked",
                    G_CALLBACK (on_chbutsup_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (chwindowsup, chwindowsup, "chwindowsup");
  GLADE_HOOKUP_OBJECT (chwindowsup, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (chwindowsup, chtreeview11, "chtreeview11");
  GLADE_HOOKUP_OBJECT (chwindowsup, label22, "label22");
  GLADE_HOOKUP_OBJECT (chwindowsup, chbutret, "chbutret");
  GLADE_HOOKUP_OBJECT (chwindowsup, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (chwindowsup, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (chwindowsup, image2, "image2");
  GLADE_HOOKUP_OBJECT (chwindowsup, label24, "label24");
  GLADE_HOOKUP_OBJECT (chwindowsup, chbutsup, "chbutsup");
  GLADE_HOOKUP_OBJECT (chwindowsup, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (chwindowsup, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (chwindowsup, image1, "image1");
  GLADE_HOOKUP_OBJECT (chwindowsup, label23, "label23");

  return chwindowsup;
}

