/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_cmfenetre_ajout (void);
GtkWidget* create_cmfenetre_afficher (void);
GtkWidget* create_cmwindow3 (void);
GtkWidget* create_cmwindow4 (void);
GtkWidget* create_chwindowsup (void);
