/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_abdouwindow1 (void);
GtkWidget* create_abdouwindow2 (void);
GtkWidget* create_abdouwindow3 (void);
GtkWidget* create_abdouwindow4 (void);
GtkWidget* create_abdouwindow5 (void);
GtkWidget* create_abdouwindow6 (void);
