/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_abdouwindow1 (void)
{
  GtkWidget *abdouwindow1;
  GtkWidget *fixed1;
  GtkWidget *Prestation_vol;
  GtkWidget *abdoufacture;
  GtkWidget *pres_heber;
  GtkWidget *abdoudeconnecter;

  abdouwindow1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow1), _("window1"));
  gtk_window_set_position (GTK_WINDOW (abdouwindow1), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (abdouwindow1), 1200, 1000);

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (abdouwindow1), fixed1);

  Prestation_vol = gtk_button_new_with_mnemonic (_("Prestation vol"));
  gtk_widget_show (Prestation_vol);
  gtk_fixed_put (GTK_FIXED (fixed1), Prestation_vol, 128, 104);
  gtk_widget_set_size_request (Prestation_vol, 128, 29);

  abdoufacture = gtk_button_new_from_stock ("mes factures");
  gtk_widget_show (abdoufacture);
  gtk_fixed_put (GTK_FIXED (fixed1), abdoufacture, 128, 168);
  gtk_widget_set_size_request (abdoufacture, 128, 37);

  pres_heber = gtk_button_new_with_mnemonic (_("Prestation hotel"));
  gtk_widget_show (pres_heber);
  gtk_fixed_put (GTK_FIXED (fixed1), pres_heber, 128, 40);
  gtk_widget_set_size_request (pres_heber, 128, 29);

  abdoudeconnecter = gtk_button_new_with_mnemonic (_("deconnecter"));
  gtk_widget_show (abdoudeconnecter);
  gtk_fixed_put (GTK_FIXED (fixed1), abdoudeconnecter, 128, 240);
  gtk_widget_set_size_request (abdoudeconnecter, 136, 37);

  g_signal_connect ((gpointer) abdoufacture, "clicked",
                    G_CALLBACK (on_abdoufacture_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdoudeconnecter, "clicked",
                    G_CALLBACK (on_abdoudeconnecter_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow1, abdouwindow1, "abdouwindow1");
  GLADE_HOOKUP_OBJECT (abdouwindow1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (abdouwindow1, Prestation_vol, "Prestation_vol");
  GLADE_HOOKUP_OBJECT (abdouwindow1, abdoufacture, "abdoufacture");
  GLADE_HOOKUP_OBJECT (abdouwindow1, pres_heber, "pres_heber");
  GLADE_HOOKUP_OBJECT (abdouwindow1, abdoudeconnecter, "abdoudeconnecter");

  return abdouwindow1;
}

GtkWidget*
create_abdouwindow2 (void)
{
  GtkWidget *abdouwindow2;
  GtkWidget *fixed2;
  GtkWidget *abdoutreeview1;
  GtkWidget *abdousupprimer;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image2;
  GtkWidget *label3;
  GtkWidget *abdoumodifier;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image4;
  GtkWidget *label5;
  GtkWidget *abdouprecedent;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image3;
  GtkWidget *back;
  GtkWidget *abdouafficher1;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image5;
  GtkWidget *label19;

  abdouwindow2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow2), _("window2"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (abdouwindow2), fixed2);

  abdoutreeview1 = gtk_tree_view_new ();
  gtk_widget_show (abdoutreeview1);
  gtk_fixed_put (GTK_FIXED (fixed2), abdoutreeview1, 32, 104);
  gtk_widget_set_size_request (abdoutreeview1, 688, 232);

  abdousupprimer = gtk_button_new ();
  gtk_widget_show (abdousupprimer);
  gtk_fixed_put (GTK_FIXED (fixed2), abdousupprimer, 208, 408);
  gtk_widget_set_size_request (abdousupprimer, 112, 37);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (abdousupprimer), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image2 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox1), image2, FALSE, FALSE, 0);

  label3 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label3);
  gtk_box_pack_start (GTK_BOX (hbox1), label3, FALSE, FALSE, 0);

  abdoumodifier = gtk_button_new ();
  gtk_widget_show (abdoumodifier);
  gtk_fixed_put (GTK_FIXED (fixed2), abdoumodifier, 376, 408);
  gtk_widget_set_size_request (abdoumodifier, 96, 37);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (abdoumodifier), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox3), image4, FALSE, FALSE, 0);

  label5 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label5);
  gtk_box_pack_start (GTK_BOX (hbox3), label5, FALSE, FALSE, 0);

  abdouprecedent = gtk_button_new ();
  gtk_widget_show (abdouprecedent);
  gtk_fixed_put (GTK_FIXED (fixed2), abdouprecedent, 32, 408);
  gtk_widget_set_size_request (abdouprecedent, 112, 37);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (abdouprecedent), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image3 = gtk_image_new_from_stock ("gtk-go-back", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox2), image3, FALSE, FALSE, 0);

  back = gtk_label_new_with_mnemonic (_("prec\303\251dent"));
  gtk_widget_show (back);
  gtk_box_pack_start (GTK_BOX (hbox2), back, FALSE, FALSE, 0);

  abdouafficher1 = gtk_button_new ();
  gtk_widget_show (abdouafficher1);
  gtk_fixed_put (GTK_FIXED (fixed2), abdouafficher1, 544, 408);
  gtk_widget_set_size_request (abdouafficher1, 104, 37);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (abdouafficher1), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image5 = gtk_image_new_from_stock ("gtk-media-play", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox4), image5, FALSE, FALSE, 0);

  label19 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label19);
  gtk_box_pack_start (GTK_BOX (hbox4), label19, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) abdousupprimer, "clicked",
                    G_CALLBACK (on_abdousupprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdoumodifier, "clicked",
                    G_CALLBACK (on_abdoumodifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouprecedent, "clicked",
                    G_CALLBACK (on_abdouprecedent_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouafficher1, "clicked",
                    G_CALLBACK (on_abdouafficher1_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow2, abdouwindow2, "abdouwindow2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdoutreeview1, "abdoutreeview1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdousupprimer, "abdousupprimer");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image2, "image2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, label3, "label3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdoumodifier, "abdoumodifier");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image4, "image4");
  GLADE_HOOKUP_OBJECT (abdouwindow2, label5, "label5");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdouprecedent, "abdouprecedent");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image3, "image3");
  GLADE_HOOKUP_OBJECT (abdouwindow2, back, "back");
  GLADE_HOOKUP_OBJECT (abdouwindow2, abdouafficher1, "abdouafficher1");
  GLADE_HOOKUP_OBJECT (abdouwindow2, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (abdouwindow2, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (abdouwindow2, image5, "image5");
  GLADE_HOOKUP_OBJECT (abdouwindow2, label19, "label19");

  return abdouwindow2;
}

GtkWidget*
create_abdouwindow3 (void)
{
  GtkWidget *abdouwindow3;
  GtkWidget *fixed3;
  GtkWidget *abdousupp;
  GtkWidget *abdouid_supprimer;
  GtkWidget *abdouprecedent1;
  GtkWidget *abdouconfirmer;

  abdouwindow3 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow3), _("window3"));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (abdouwindow3), fixed3);

  abdousupp = gtk_entry_new ();
  gtk_widget_show (abdousupp);
  gtk_fixed_put (GTK_FIXED (fixed3), abdousupp, 136, 120);
  gtk_widget_set_size_request (abdousupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdousupp), 8226);

  abdouid_supprimer = gtk_label_new (_("id supprimer"));
  gtk_widget_show (abdouid_supprimer);
  gtk_fixed_put (GTK_FIXED (fixed3), abdouid_supprimer, 136, 56);
  gtk_widget_set_size_request (abdouid_supprimer, 120, 16);

  abdouprecedent1 = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (abdouprecedent1);
  gtk_fixed_put (GTK_FIXED (fixed3), abdouprecedent1, 112, 208);
  gtk_widget_set_size_request (abdouprecedent1, 104, 29);

  abdouconfirmer = gtk_button_new_with_mnemonic (_("appliquer"));
  gtk_widget_show (abdouconfirmer);
  gtk_fixed_put (GTK_FIXED (fixed3), abdouconfirmer, 264, 208);
  gtk_widget_set_size_request (abdouconfirmer, 112, 32);

  g_signal_connect ((gpointer) abdouprecedent1, "clicked",
                    G_CALLBACK (on_abdouprecedent1_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouconfirmer, "clicked",
                    G_CALLBACK (on_abdouconfirmer_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow3, abdouwindow3, "abdouwindow3");
  GLADE_HOOKUP_OBJECT (abdouwindow3, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdousupp, "abdousupp");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdouid_supprimer, "abdouid_supprimer");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdouprecedent1, "abdouprecedent1");
  GLADE_HOOKUP_OBJECT (abdouwindow3, abdouconfirmer, "abdouconfirmer");

  return abdouwindow3;
}

GtkWidget*
create_abdouwindow4 (void)
{
  GtkWidget *abdouwindow4;
  GtkWidget *fixed4;
  GtkWidget *abdounid;
  GtkWidget *abdounnom;
  GtkWidget *abdounprenom;
  GtkWidget *abdounreservation;
  GtkWidget *abdounmontant_total;
  GtkWidget *abdounmontant_ttc;
  GtkObject *abdounjour_adj;
  GtkWidget *abdounjour;
  GtkObject *abdounmois_adj;
  GtkWidget *abdounmois;
  GtkObject *abdounannee_adj;
  GtkWidget *abdounannee;
  GtkWidget *abdouid;
  GtkWidget *abdoulabel8;
  GtkWidget *abdoulabel9;
  GtkWidget *abdoulabel10;
  GtkWidget *abdoulabel14;
  GtkWidget *abdoulabel16;
  GtkWidget *abdoulabel13;
  GtkWidget *abdoulabel17;
  GtkWidget *abdoulabel11;
  GtkWidget *abdoumodifierr;
  GtkWidget *abdoulabel15;
  GtkWidget *abdoulabel18;
  GtkWidget *abdouvalider;
  GtkWidget *abdoulabel12;
  GtkWidget *abdou0;

  abdouwindow4 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow4), _("window4"));

  fixed4 = gtk_fixed_new ();
  gtk_widget_show (fixed4);
  gtk_container_add (GTK_CONTAINER (abdouwindow4), fixed4);

  abdounid = gtk_entry_new ();
  gtk_widget_show (abdounid);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounid, 120, 40);
  gtk_widget_set_size_request (abdounid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounid), 8226);

  abdounnom = gtk_entry_new ();
  gtk_widget_show (abdounnom);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounnom, 120, 96);
  gtk_widget_set_size_request (abdounnom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounnom), 8226);

  abdounprenom = gtk_entry_new ();
  gtk_widget_show (abdounprenom);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounprenom, 120, 152);
  gtk_widget_set_size_request (abdounprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounprenom), 8226);

  abdounreservation = gtk_entry_new ();
  gtk_widget_show (abdounreservation);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounreservation, 120, 272);
  gtk_widget_set_size_request (abdounreservation, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounreservation), 8226);

  abdounmontant_total = gtk_entry_new ();
  gtk_widget_show (abdounmontant_total);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounmontant_total, 120, 328);
  gtk_widget_set_size_request (abdounmontant_total, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounmontant_total), 8226);

  abdounmontant_ttc = gtk_entry_new ();
  gtk_widget_show (abdounmontant_ttc);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounmontant_ttc, 120, 384);
  gtk_widget_set_size_request (abdounmontant_ttc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounmontant_ttc), 8226);

  abdounjour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  abdounjour = gtk_spin_button_new (GTK_ADJUSTMENT (abdounjour_adj), 1, 0);
  gtk_widget_show (abdounjour);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounjour, 152, 224);
  gtk_widget_set_size_request (abdounjour, 60, 27);

  abdounmois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  abdounmois = gtk_spin_button_new (GTK_ADJUSTMENT (abdounmois_adj), 1, 0);
  gtk_widget_show (abdounmois);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounmois, 312, 224);
  gtk_widget_set_size_request (abdounmois, 60, 27);

  abdounannee_adj = gtk_adjustment_new (1, 2019, 2030, 1, 10, 10);
  abdounannee = gtk_spin_button_new (GTK_ADJUSTMENT (abdounannee_adj), 1, 0);
  gtk_widget_show (abdounannee);
  gtk_fixed_put (GTK_FIXED (fixed4), abdounannee, 464, 224);
  gtk_widget_set_size_request (abdounannee, 60, 27);

  abdouid = gtk_entry_new ();
  gtk_widget_show (abdouid);
  gtk_fixed_put (GTK_FIXED (fixed4), abdouid, 464, 32);
  gtk_widget_set_size_request (abdouid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouid), 8226);

  abdoulabel8 = gtk_label_new (_("id "));
  gtk_widget_show (abdoulabel8);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel8, 48, 48);
  gtk_widget_set_size_request (abdoulabel8, 41, 17);

  abdoulabel9 = gtk_label_new (_("nom"));
  gtk_widget_show (abdoulabel9);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel9, 40, 104);
  gtk_widget_set_size_request (abdoulabel9, 41, 17);

  abdoulabel10 = gtk_label_new (_("prenom"));
  gtk_widget_show (abdoulabel10);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel10, 32, 152);
  gtk_widget_set_size_request (abdoulabel10, 64, 25);

  abdoulabel14 = gtk_label_new (_("date"));
  gtk_widget_show (abdoulabel14);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel14, 16, 224);
  gtk_widget_set_size_request (abdoulabel14, 64, 25);

  abdoulabel16 = gtk_label_new (_("reservation"));
  gtk_widget_show (abdoulabel16);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel16, 16, 264);
  gtk_widget_set_size_request (abdoulabel16, 96, 33);

  abdoulabel13 = gtk_label_new (_("montant total"));
  gtk_widget_show (abdoulabel13);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel13, 0, 320);
  gtk_widget_set_size_request (abdoulabel13, 128, 33);

  abdoulabel17 = gtk_label_new (_("montant TTC"));
  gtk_widget_show (abdoulabel17);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel17, 0, 376);
  gtk_widget_set_size_request (abdoulabel17, 128, 33);

  abdoulabel11 = gtk_label_new (_("jour"));
  gtk_widget_show (abdoulabel11);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel11, 88, 224);
  gtk_widget_set_size_request (abdoulabel11, 56, 25);

  abdoumodifierr = gtk_button_new_with_mnemonic (_("modifier"));
  gtk_widget_show (abdoumodifierr);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoumodifierr, 144, 448);
  gtk_widget_set_size_request (abdoumodifierr, 96, 29);

  abdoulabel15 = gtk_label_new (_("mois"));
  gtk_widget_show (abdoulabel15);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel15, 248, 224);
  gtk_widget_set_size_request (abdoulabel15, 56, 25);

  abdoulabel18 = gtk_label_new (_("id facture"));
  gtk_widget_show (abdoulabel18);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel18, 384, 32);
  gtk_widget_set_size_request (abdoulabel18, 80, 25);

  abdouvalider = gtk_button_new_with_mnemonic (_("rechercher"));
  gtk_widget_show (abdouvalider);
  gtk_fixed_put (GTK_FIXED (fixed4), abdouvalider, 496, 80);
  gtk_widget_set_size_request (abdouvalider, 96, 29);

  abdoulabel12 = gtk_label_new (_("annee"));
  gtk_widget_show (abdoulabel12);
  gtk_fixed_put (GTK_FIXED (fixed4), abdoulabel12, 392, 224);
  gtk_widget_set_size_request (abdoulabel12, 64, 25);

  abdou0 = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (abdou0);
  gtk_fixed_put (GTK_FIXED (fixed4), abdou0, 24, 496);
  gtk_widget_set_size_request (abdou0, 96, 29);

  g_signal_connect ((gpointer) abdoumodifierr, "clicked",
                    G_CALLBACK (on_abdoumodifierr_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouvalider, "clicked",
                    G_CALLBACK (on_abdouvalider_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdou0, "clicked",
                    G_CALLBACK (on_abdou0_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow4, abdouwindow4, "abdouwindow4");
  GLADE_HOOKUP_OBJECT (abdouwindow4, fixed4, "fixed4");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounid, "abdounid");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounnom, "abdounnom");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounprenom, "abdounprenom");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounreservation, "abdounreservation");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounmontant_total, "abdounmontant_total");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounmontant_ttc, "abdounmontant_ttc");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounjour, "abdounjour");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounmois, "abdounmois");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdounannee, "abdounannee");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdouid, "abdouid");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel8, "abdoulabel8");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel9, "abdoulabel9");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel10, "abdoulabel10");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel14, "abdoulabel14");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel16, "abdoulabel16");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel13, "abdoulabel13");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel17, "abdoulabel17");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel11, "abdoulabel11");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoumodifierr, "abdoumodifierr");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel15, "abdoulabel15");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel18, "abdoulabel18");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdouvalider, "abdouvalider");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdoulabel12, "abdoulabel12");
  GLADE_HOOKUP_OBJECT (abdouwindow4, abdou0, "abdou0");

  return abdouwindow4;
}

GtkWidget*
create_abdouwindow5 (void)
{
  GtkWidget *abdouwindow5;
  GtkWidget *fixed5;
  GtkWidget *abdouid;
  GtkWidget *abdouprenom;
  GtkObject *abdoujour_adj;
  GtkWidget *abdoujour;
  GtkObject *abdoumois_adj;
  GtkWidget *abdoumois;
  GtkObject *abdouannee_adj;
  GtkWidget *abdouannee;
  GtkWidget *abdoureservation;
  GtkWidget *abdoumontant_total;
  GtkWidget *abdoumontant_ttc;
  GtkWidget *label29;
  GtkWidget *abdounom;
  GtkWidget *label30;
  GtkWidget *label31;
  GtkWidget *label32;
  GtkWidget *label26;
  GtkWidget *label28;
  GtkWidget *label27;
  GtkWidget *_1546;
  GtkWidget *label33;
  GtkWidget *_87897;
  GtkWidget *abdouerreur1;
  GtkWidget *abdouerreur2;
  GtkWidget *abdouerreur3;
  GtkWidget *abdouerreur4;
  GtkWidget *abdouerreur5;
  GtkWidget *abdouerreur6;
  GtkWidget *abdouprecedent2;
  GtkWidget *abdouajoute;

  abdouwindow5 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow5), _("window1"));

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (abdouwindow5), fixed5);

  abdouid = gtk_entry_new ();
  gtk_widget_show (abdouid);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouid, 128, 72);
  gtk_widget_set_size_request (abdouid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouid), 8226);

  abdouprenom = gtk_entry_new ();
  gtk_widget_show (abdouprenom);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouprenom, 416, 176);
  gtk_widget_set_size_request (abdouprenom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouprenom), 8226);

  abdoujour_adj = gtk_adjustment_new (1, 1, 31, 1, 10, 10);
  abdoujour = gtk_spin_button_new (GTK_ADJUSTMENT (abdoujour_adj), 1, 0);
  gtk_widget_show (abdoujour);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoujour, 152, 272);
  gtk_widget_set_size_request (abdoujour, 60, 27);

  abdoumois_adj = gtk_adjustment_new (1, 1, 12, 1, 10, 10);
  abdoumois = gtk_spin_button_new (GTK_ADJUSTMENT (abdoumois_adj), 1, 0);
  gtk_widget_show (abdoumois);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoumois, 280, 272);
  gtk_widget_set_size_request (abdoumois, 60, 27);

  abdouannee_adj = gtk_adjustment_new (1, 2019, 2030, 1, 10, 10);
  abdouannee = gtk_spin_button_new (GTK_ADJUSTMENT (abdouannee_adj), 1, 0);
  gtk_widget_show (abdouannee);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouannee, 392, 272);
  gtk_widget_set_size_request (abdouannee, 60, 27);

  abdoureservation = gtk_entry_new ();
  gtk_widget_show (abdoureservation);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoureservation, 120, 344);
  gtk_widget_set_size_request (abdoureservation, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoureservation), 8226);

  abdoumontant_total = gtk_entry_new ();
  gtk_widget_show (abdoumontant_total);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoumontant_total, 416, 344);
  gtk_widget_set_size_request (abdoumontant_total, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoumontant_total), 8226);

  abdoumontant_ttc = gtk_entry_new ();
  gtk_widget_show (abdoumontant_ttc);
  gtk_fixed_put (GTK_FIXED (fixed5), abdoumontant_ttc, 416, 416);
  gtk_widget_set_size_request (abdoumontant_ttc, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoumontant_ttc), 8226);

  label29 = gtk_label_new (_("date"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed5), label29, 24, 280);
  gtk_widget_set_size_request (label29, 49, 17);

  abdounom = gtk_entry_new ();
  gtk_widget_show (abdounom);
  gtk_fixed_put (GTK_FIXED (fixed5), abdounom, 128, 176);
  gtk_widget_set_size_request (abdounom, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdounom), 8226);

  label30 = gtk_label_new (_("jour"));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed5), label30, 96, 280);
  gtk_widget_set_size_request (label30, 49, 17);

  label31 = gtk_label_new (_("mois"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed5), label31, 224, 280);
  gtk_widget_set_size_request (label31, 49, 17);

  label32 = gtk_label_new (_("annee"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed5), label32, 344, 280);
  gtk_widget_set_size_request (label32, 49, 17);

  label26 = gtk_label_new (_("id facture"));
  gtk_widget_show (label26);
  gtk_fixed_put (GTK_FIXED (fixed5), label26, 16, 72);
  gtk_widget_set_size_request (label26, 88, 25);

  label28 = gtk_label_new (_("nom"));
  gtk_widget_show (label28);
  gtk_fixed_put (GTK_FIXED (fixed5), label28, 40, 184);
  gtk_widget_set_size_request (label28, 49, 17);

  label27 = gtk_label_new (_("prenom"));
  gtk_widget_show (label27);
  gtk_fixed_put (GTK_FIXED (fixed5), label27, 336, 176);
  gtk_widget_set_size_request (label27, 72, 25);

  _1546 = gtk_label_new (_("montant total"));
  gtk_widget_show (_1546);
  gtk_fixed_put (GTK_FIXED (fixed5), _1546, 296, 344);
  gtk_widget_set_size_request (_1546, 112, 25);

  label33 = gtk_label_new (_("id reservation"));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed5), label33, 8, 344);
  gtk_widget_set_size_request (label33, 112, 25);

  _87897 = gtk_label_new (_("montant ttc"));
  gtk_widget_show (_87897);
  gtk_fixed_put (GTK_FIXED (fixed5), _87897, 296, 416);
  gtk_widget_set_size_request (_87897, 112, 25);

  abdouerreur1 = gtk_label_new ("");
  gtk_widget_show (abdouerreur1);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur1, 128, 104);
  gtk_widget_set_size_request (abdouerreur1, 160, 17);

  abdouerreur2 = gtk_label_new ("");
  gtk_widget_show (abdouerreur2);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur2, 128, 208);
  gtk_widget_set_size_request (abdouerreur2, 160, 17);

  abdouerreur3 = gtk_label_new ("");
  gtk_widget_show (abdouerreur3);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur3, 416, 200);
  gtk_widget_set_size_request (abdouerreur3, 160, 25);

  abdouerreur4 = gtk_label_new ("");
  gtk_widget_show (abdouerreur4);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur4, 120, 376);
  gtk_widget_set_size_request (abdouerreur4, 160, 25);

  abdouerreur5 = gtk_label_new ("");
  gtk_widget_show (abdouerreur5);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur5, 416, 376);
  gtk_widget_set_size_request (abdouerreur5, 160, 24);

  abdouerreur6 = gtk_label_new ("");
  gtk_widget_show (abdouerreur6);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouerreur6, 416, 456);
  gtk_widget_set_size_request (abdouerreur6, 160, 24);

  abdouprecedent2 = gtk_button_new_with_mnemonic (_("precedent"));
  gtk_widget_show (abdouprecedent2);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouprecedent2, 48, 504);
  gtk_widget_set_size_request (abdouprecedent2, 136, 29);

  abdouajoute = gtk_button_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (abdouajoute);
  gtk_fixed_put (GTK_FIXED (fixed5), abdouajoute, 424, 504);
  gtk_widget_set_size_request (abdouajoute, 112, 29);

  g_signal_connect ((gpointer) abdouprecedent2, "clicked",
                    G_CALLBACK (on_abdouprecedent2_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouajoute, "clicked",
                    G_CALLBACK (on_abdouajoute_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow5, abdouwindow5, "abdouwindow5");
  GLADE_HOOKUP_OBJECT (abdouwindow5, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouid, "abdouid");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouprenom, "abdouprenom");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoujour, "abdoujour");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoumois, "abdoumois");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouannee, "abdouannee");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoureservation, "abdoureservation");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoumontant_total, "abdoumontant_total");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdoumontant_ttc, "abdoumontant_ttc");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label29, "label29");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdounom, "abdounom");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label30, "label30");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label31, "label31");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label32, "label32");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label26, "label26");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label28, "label28");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label27, "label27");
  GLADE_HOOKUP_OBJECT (abdouwindow5, _1546, "_1546");
  GLADE_HOOKUP_OBJECT (abdouwindow5, label33, "label33");
  GLADE_HOOKUP_OBJECT (abdouwindow5, _87897, "_87897");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur1, "abdouerreur1");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur2, "abdouerreur2");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur3, "abdouerreur3");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur4, "abdouerreur4");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur5, "abdouerreur5");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouerreur6, "abdouerreur6");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouprecedent2, "abdouprecedent2");
  GLADE_HOOKUP_OBJECT (abdouwindow5, abdouajoute, "abdouajoute");

  return abdouwindow5;
}

GtkWidget*
create_abdouwindow6 (void)
{
  GtkWidget *abdouwindow6;
  GtkWidget *fixed6;
  GtkWidget *abdouloginentry;
  GtkWidget *abdoumotdepasse;
  GtkWidget *abdouerreuruser;
  GtkWidget *label34;
  GtkWidget *label35;
  GtkWidget *abdoulogin;
  GtkWidget *abdouretour;

  abdouwindow6 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (abdouwindow6), _("abdouwindow6"));
  gtk_window_set_position (GTK_WINDOW (abdouwindow6), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (abdouwindow6), 1200, 1000);

  fixed6 = gtk_fixed_new ();
  gtk_widget_show (fixed6);
  gtk_container_add (GTK_CONTAINER (abdouwindow6), fixed6);

  abdouloginentry = gtk_entry_new ();
  gtk_widget_show (abdouloginentry);
  gtk_fixed_put (GTK_FIXED (fixed6), abdouloginentry, 528, 224);
  gtk_widget_set_size_request (abdouloginentry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdouloginentry), 8226);

  abdoumotdepasse = gtk_entry_new ();
  gtk_widget_show (abdoumotdepasse);
  gtk_fixed_put (GTK_FIXED (fixed6), abdoumotdepasse, 528, 328);
  gtk_widget_set_size_request (abdoumotdepasse, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (abdoumotdepasse), 8226);

  abdouerreuruser = gtk_label_new ("");
  gtk_widget_show (abdouerreuruser);
  gtk_fixed_put (GTK_FIXED (fixed6), abdouerreuruser, 512, 416);
  gtk_widget_set_size_request (abdouerreuruser, 312, 49);

  label34 = gtk_label_new (_("Login"));
  gtk_widget_show (label34);
  gtk_fixed_put (GTK_FIXED (fixed6), label34, 392, 224);
  gtk_widget_set_size_request (label34, 72, 25);

  label35 = gtk_label_new (_("Mot de passe"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed6), label35, 376, 328);
  gtk_widget_set_size_request (label35, 96, 25);

  abdoulogin = gtk_button_new_with_mnemonic (_("Login "));
  gtk_widget_show (abdoulogin);
  gtk_fixed_put (GTK_FIXED (fixed6), abdoulogin, 656, 512);
  gtk_widget_set_size_request (abdoulogin, 68, 29);

  abdouretour = gtk_button_new_with_mnemonic (_("retour"));
  gtk_widget_show (abdouretour);
  gtk_fixed_put (GTK_FIXED (fixed6), abdouretour, 328, 512);
  gtk_widget_set_size_request (abdouretour, 104, 29);

  g_signal_connect ((gpointer) abdoulogin, "clicked",
                    G_CALLBACK (on_abdoulogin_clicked),
                    NULL);
  g_signal_connect ((gpointer) abdouretour, "clicked",
                    G_CALLBACK (on_abdouretour_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (abdouwindow6, abdouwindow6, "abdouwindow6");
  GLADE_HOOKUP_OBJECT (abdouwindow6, fixed6, "fixed6");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdouloginentry, "abdouloginentry");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdoumotdepasse, "abdoumotdepasse");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdouerreuruser, "abdouerreuruser");
  GLADE_HOOKUP_OBJECT (abdouwindow6, label34, "label34");
  GLADE_HOOKUP_OBJECT (abdouwindow6, label35, "label35");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdoulogin, "abdoulogin");
  GLADE_HOOKUP_OBJECT (abdouwindow6, abdouretour, "abdouretour");

  return abdouwindow6;
}

